package commands

import (
	"context"
	"fmt"
	"strings"
	"sync"

	beyondcorpservice "github.com/BishopFox/cloudfox/gcp/services/beyondcorpService"
	"github.com/BishopFox/cloudfox/globals"
	"github.com/BishopFox/cloudfox/internal"
	gcpinternal "github.com/BishopFox/cloudfox/internal/gcp"
	"github.com/spf13/cobra"
)

var GCPBeyondCorpCommand = &cobra.Command{
	Use:     globals.GCP_BEYONDCORP_MODULE_NAME,
	Aliases: []string{"bc", "zero-trust"},
	Short:   "Enumerate BeyondCorp Enterprise configurations",
	Long: `Enumerate BeyondCorp Enterprise configurations.

Features:
- Lists app connectors and connections
- Analyzes connection endpoints
- Identifies configuration issues`,
	Run: runGCPBeyondCorpCommand,
}

type BeyondCorpModule struct {
	gcpinternal.BaseGCPModule
	ProjectAppConnectors  map[string][]beyondcorpservice.AppConnectorInfo  // projectID -> connectors
	ProjectAppConnections map[string][]beyondcorpservice.AppConnectionInfo // projectID -> connections
	LootMap               map[string]map[string]*internal.LootFile         // projectID -> loot files
	mu                    sync.Mutex
}

type BeyondCorpOutput struct {
	Table []internal.TableFile
	Loot  []internal.LootFile
}

func (o BeyondCorpOutput) TableFiles() []internal.TableFile { return o.Table }
func (o BeyondCorpOutput) LootFiles() []internal.LootFile   { return o.Loot }

func runGCPBeyondCorpCommand(cmd *cobra.Command, args []string) {
	cmdCtx, err := gcpinternal.InitializeCommandContext(cmd, globals.GCP_BEYONDCORP_MODULE_NAME)
	if err != nil {
		return
	}

	module := &BeyondCorpModule{
		BaseGCPModule:         gcpinternal.NewBaseGCPModule(cmdCtx),
		ProjectAppConnectors:  make(map[string][]beyondcorpservice.AppConnectorInfo),
		ProjectAppConnections: make(map[string][]beyondcorpservice.AppConnectionInfo),
		LootMap:               make(map[string]map[string]*internal.LootFile),
	}
	module.Execute(cmdCtx.Ctx, cmdCtx.Logger)
}

func (m *BeyondCorpModule) Execute(ctx context.Context, logger internal.Logger) {
	m.RunProjectEnumeration(ctx, logger, m.ProjectIDs, globals.GCP_BEYONDCORP_MODULE_NAME, m.processProject)

	allConnectors := m.getAllConnectors()
	allConnections := m.getAllConnections()

	totalCount := len(allConnectors) + len(allConnections)
	if totalCount == 0 {
		logger.InfoM("No BeyondCorp resources found", globals.GCP_BEYONDCORP_MODULE_NAME)
		return
	}

	// Count public resources
	publicConnectorCount := 0
	publicConnectionCount := 0
	for _, connector := range allConnectors {
		if connector.PublicAccess {
			publicConnectorCount++
		}
	}
	for _, conn := range allConnections {
		if conn.PublicAccess {
			publicConnectionCount++
		}
	}

	logger.SuccessM(fmt.Sprintf("Found %d connector(s), %d connection(s)",
		len(allConnectors), len(allConnections)),
		globals.GCP_BEYONDCORP_MODULE_NAME)

	if publicConnectorCount > 0 || publicConnectionCount > 0 {
		logger.InfoM(fmt.Sprintf("[FINDING] Found %d public connector(s), %d public connection(s)!",
			publicConnectorCount, publicConnectionCount), globals.GCP_BEYONDCORP_MODULE_NAME)
	}

	m.writeOutput(ctx, logger)
}

func (m *BeyondCorpModule) getAllConnectors() []beyondcorpservice.AppConnectorInfo {
	var all []beyondcorpservice.AppConnectorInfo
	for _, connectors := range m.ProjectAppConnectors {
		all = append(all, connectors...)
	}
	return all
}

func (m *BeyondCorpModule) getAllConnections() []beyondcorpservice.AppConnectionInfo {
	var all []beyondcorpservice.AppConnectionInfo
	for _, connections := range m.ProjectAppConnections {
		all = append(all, connections...)
	}
	return all
}

func (m *BeyondCorpModule) processProject(ctx context.Context, projectID string, logger internal.Logger) {
	if globals.GCP_VERBOSITY >= globals.GCP_VERBOSE_ERRORS {
		logger.InfoM(fmt.Sprintf("Enumerating BeyondCorp in project: %s", projectID), globals.GCP_BEYONDCORP_MODULE_NAME)
	}

	svc := beyondcorpservice.New()

	m.mu.Lock()
	// Initialize loot for this project
	if m.LootMap[projectID] == nil {
		m.LootMap[projectID] = make(map[string]*internal.LootFile)
		m.LootMap[projectID]["beyondcorp-details"] = &internal.LootFile{
			Name:     "beyondcorp-details",
			Contents: "# BeyondCorp Commands\n# Generated by CloudFox\n# WARNING: Only use with proper authorization\n\n",
		}
	}
	m.mu.Unlock()

	// Get app connectors
	connectors, err := svc.ListAppConnectors(projectID)
	if err != nil {
		m.CommandCounter.Error++
		gcpinternal.HandleGCPError(err, logger, globals.GCP_BEYONDCORP_MODULE_NAME,
			fmt.Sprintf("Could not list app connectors in project %s", projectID))
	}
	m.mu.Lock()
	m.ProjectAppConnectors[projectID] = connectors
	for _, connector := range connectors {
		m.addConnectorToLoot(projectID, connector)
	}
	m.mu.Unlock()

	// Get app connections
	connections, err := svc.ListAppConnections(projectID)
	if err != nil {
		m.CommandCounter.Error++
		gcpinternal.HandleGCPError(err, logger, globals.GCP_BEYONDCORP_MODULE_NAME,
			fmt.Sprintf("Could not list app connections in project %s", projectID))
	}
	m.mu.Lock()
	m.ProjectAppConnections[projectID] = connections
	for _, conn := range connections {
		m.addConnectionToLoot(projectID, conn)
	}
	m.mu.Unlock()
}

func (m *BeyondCorpModule) addConnectionToLoot(projectID string, conn beyondcorpservice.AppConnectionInfo) {
	lootFile := m.LootMap[projectID]["beyondcorp-details"]
	if lootFile == nil {
		return
	}
	lootFile.Contents += fmt.Sprintf(
		"# =============================================================================\n"+
			"# CONNECTION: %s\n"+
			"# =============================================================================\n"+
			"# Project: %s\n"+
			"# Location: %s\n"+
			"# State: %s\n"+
			"# Endpoint: %s\n"+
			"# Gateway: %s\n"+
			"# Connectors: %s\n",
		conn.Name, conn.ProjectID, conn.Location, conn.State,
		conn.ApplicationEndpoint, conn.Gateway, strings.Join(conn.Connectors, ", "))

	lootFile.Contents += fmt.Sprintf(`
# === ENUMERATION COMMANDS ===

# Describe this app connection:
gcloud beta beyondcorp app connections describe %s --location=%s --project=%s

# List IAM policy for this connection:
gcloud beta beyondcorp app connections get-iam-policy %s --location=%s --project=%s

# List all app connectors in the project:
gcloud beta beyondcorp app connectors list --location=%s --project=%s

# List all app connections in the project:
gcloud beta beyondcorp app connections list --location=%s --project=%s

`, conn.Name, conn.Location, conn.ProjectID,
		conn.Name, conn.Location, conn.ProjectID,
		conn.Location, conn.ProjectID,
		conn.Location, conn.ProjectID)

	// Exploitation commands
	if conn.ApplicationEndpoint != "" {
		lootFile.Contents += fmt.Sprintf(
			"# === EXPLOIT COMMANDS ===\n\n"+
				"# Test connectivity to application endpoint:\n"+
				"curl -v %s\n\n"+
				"# Scan endpoint for open ports (if IP-based):\n"+
				"nmap -sV %s\n\n",
			conn.ApplicationEndpoint, conn.ApplicationEndpoint)
	}

	if conn.PublicAccess {
		lootFile.Contents += "# [FINDING] This connection has PUBLIC access!\n" +
			"# Check IAM bindings for allUsers/allAuthenticatedUsers\n\n"
	}
}

func (m *BeyondCorpModule) addConnectorToLoot(projectID string, connector beyondcorpservice.AppConnectorInfo) {
	lootFile := m.LootMap[projectID]["beyondcorp-details"]
	if lootFile == nil {
		return
	}
	lootFile.Contents += fmt.Sprintf(
		"# =============================================================================\n"+
			"# CONNECTOR: %s\n"+
			"# =============================================================================\n"+
			"# Project: %s\n"+
			"# Location: %s\n"+
			"# State: %s\n"+
			"# Service Account: %s\n",
		connector.Name, connector.ProjectID, connector.Location,
		connector.State, connector.PrincipalInfo)

	lootFile.Contents += fmt.Sprintf(`
# Describe this connector:
gcloud beta beyondcorp app connectors describe %s --location=%s --project=%s

# Get IAM policy for this connector:
gcloud beta beyondcorp app connectors get-iam-policy %s --location=%s --project=%s

`, connector.Name, connector.Location, connector.ProjectID,
		connector.Name, connector.Location, connector.ProjectID)

	if connector.PublicAccess {
		lootFile.Contents += "# [FINDING] This connector has PUBLIC access!\n\n"
	}
}

func (m *BeyondCorpModule) writeOutput(ctx context.Context, logger internal.Logger) {
	if m.Hierarchy != nil && !m.FlatOutput {
		m.writeHierarchicalOutput(ctx, logger)
	} else {
		m.writeFlatOutput(ctx, logger)
	}
}

func (m *BeyondCorpModule) getConnectorsHeader() []string {
	return []string{"Project", "Name", "Location", "State", "Service Account", "IAM Binding Role", "IAM Binding Principal", "Public"}
}

func (m *BeyondCorpModule) getConnectionsHeader() []string {
	return []string{"Project", "Name", "Location", "State", "Endpoint", "Gateway", "IAM Binding Role", "IAM Binding Principal", "Public"}
}

func (m *BeyondCorpModule) connectorsToTableBody(connectors []beyondcorpservice.AppConnectorInfo) [][]string {
	var body [][]string
	for _, connector := range connectors {
		publicAccess := "No"
		if connector.PublicAccess {
			publicAccess = "Yes"
		}

		if len(connector.IAMBindings) == 0 {
			body = append(body, []string{
				m.GetProjectName(connector.ProjectID),
				connector.Name,
				connector.Location,
				connector.State,
				connector.PrincipalInfo,
				"-",
				"-",
				publicAccess,
			})
		} else {
			for _, binding := range connector.IAMBindings {
				for _, member := range binding.Members {
					body = append(body, []string{
						m.GetProjectName(connector.ProjectID),
						connector.Name,
						connector.Location,
						connector.State,
						connector.PrincipalInfo,
						binding.Role,
						member,
						publicAccess,
					})
				}
			}
		}
	}
	return body
}

func (m *BeyondCorpModule) connectionsToTableBody(connections []beyondcorpservice.AppConnectionInfo) [][]string {
	var body [][]string
	for _, conn := range connections {
		publicAccess := "No"
		if conn.PublicAccess {
			publicAccess = "Yes"
		}

		if len(conn.IAMBindings) == 0 {
			body = append(body, []string{
				m.GetProjectName(conn.ProjectID),
				conn.Name,
				conn.Location,
				conn.State,
				conn.ApplicationEndpoint,
				conn.Gateway,
				"-",
				"-",
				publicAccess,
			})
		} else {
			for _, binding := range conn.IAMBindings {
				for _, member := range binding.Members {
					body = append(body, []string{
						m.GetProjectName(conn.ProjectID),
						conn.Name,
						conn.Location,
						conn.State,
						conn.ApplicationEndpoint,
						conn.Gateway,
						binding.Role,
						member,
						publicAccess,
					})
				}
			}
		}
	}
	return body
}

func (m *BeyondCorpModule) buildTablesForProject(projectID string) []internal.TableFile {
	var tableFiles []internal.TableFile

	if connectors, ok := m.ProjectAppConnectors[projectID]; ok && len(connectors) > 0 {
		tableFiles = append(tableFiles, internal.TableFile{
			Name:   "beyondcorp-connectors",
			Header: m.getConnectorsHeader(),
			Body:   m.connectorsToTableBody(connectors),
		})
	}

	if connections, ok := m.ProjectAppConnections[projectID]; ok && len(connections) > 0 {
		tableFiles = append(tableFiles, internal.TableFile{
			Name:   "beyondcorp-connections",
			Header: m.getConnectionsHeader(),
			Body:   m.connectionsToTableBody(connections),
		})
	}

	return tableFiles
}

func (m *BeyondCorpModule) writeHierarchicalOutput(ctx context.Context, logger internal.Logger) {
	outputData := internal.HierarchicalOutputData{
		OrgLevelData:     make(map[string]internal.CloudfoxOutput),
		ProjectLevelData: make(map[string]internal.CloudfoxOutput),
	}

	// Get all project IDs that have data
	projectIDs := make(map[string]bool)
	for projectID := range m.ProjectAppConnectors {
		projectIDs[projectID] = true
	}
	for projectID := range m.ProjectAppConnections {
		projectIDs[projectID] = true
	}

	for projectID := range projectIDs {
		tableFiles := m.buildTablesForProject(projectID)

		var lootFiles []internal.LootFile
		if projectLoot, ok := m.LootMap[projectID]; ok {
			for _, loot := range projectLoot {
				if loot != nil && loot.Contents != "" && !strings.HasSuffix(loot.Contents, "# WARNING: Only use with proper authorization\n\n") {
					lootFiles = append(lootFiles, *loot)
				}
			}
		}

		outputData.ProjectLevelData[projectID] = BeyondCorpOutput{Table: tableFiles, Loot: lootFiles}
	}

	pathBuilder := m.BuildPathBuilder()

	err := internal.HandleHierarchicalOutputSmart("gcp", m.Format, m.Verbosity, m.WrapTable, pathBuilder, outputData)
	if err != nil {
		logger.ErrorM(fmt.Sprintf("Error writing hierarchical output: %v", err), globals.GCP_BEYONDCORP_MODULE_NAME)
	}
}

func (m *BeyondCorpModule) writeFlatOutput(ctx context.Context, logger internal.Logger) {
	allConnectors := m.getAllConnectors()
	allConnections := m.getAllConnections()

	var tables []internal.TableFile

	if len(allConnectors) > 0 {
		tables = append(tables, internal.TableFile{
			Name:   "beyondcorp-connectors",
			Header: m.getConnectorsHeader(),
			Body:   m.connectorsToTableBody(allConnectors),
		})
	}

	if len(allConnections) > 0 {
		tables = append(tables, internal.TableFile{
			Name:   "beyondcorp-connections",
			Header: m.getConnectionsHeader(),
			Body:   m.connectionsToTableBody(allConnections),
		})
	}

	var lootFiles []internal.LootFile
	for _, projectLoot := range m.LootMap {
		for _, loot := range projectLoot {
			if loot != nil && loot.Contents != "" && !strings.HasSuffix(loot.Contents, "# WARNING: Only use with proper authorization\n\n") {
				lootFiles = append(lootFiles, *loot)
			}
		}
	}

	output := BeyondCorpOutput{Table: tables, Loot: lootFiles}

	scopeNames := make([]string, len(m.ProjectIDs))
	for i, id := range m.ProjectIDs {
		scopeNames[i] = m.GetProjectName(id)
	}

	err := internal.HandleOutputSmart("gcp", m.Format, m.OutputDirectory, m.Verbosity, m.WrapTable,
		"project", m.ProjectIDs, scopeNames, m.Account, output)
	if err != nil {
		logger.ErrorM(fmt.Sprintf("Error writing output: %v", err), globals.GCP_BEYONDCORP_MODULE_NAME)
	}
}
