package commands

import (
	"context"
	"fmt"
	"strings"
	"sync"

	iapservice "github.com/BishopFox/cloudfox/gcp/services/iapService"
	"github.com/BishopFox/cloudfox/globals"
	"github.com/BishopFox/cloudfox/internal"
	gcpinternal "github.com/BishopFox/cloudfox/internal/gcp"
	"github.com/spf13/cobra"
)

var GCPIAPCommand = &cobra.Command{
	Use:     globals.GCP_IAP_MODULE_NAME,
	Aliases: []string{"identity-aware-proxy"},
	Short:   "Enumerate Identity-Aware Proxy configurations",
	Long: `Enumerate Identity-Aware Proxy (IAP) configurations.

Features:
- Lists IAP tunnel destination groups
- Analyzes IAP settings and bindings
- Identifies overly permissive tunnel configurations
- Checks for public access to IAP resources`,
	Run: runGCPIAPCommand,
}

type IAPModule struct {
	gcpinternal.BaseGCPModule
	ProjectTunnelDestGroups map[string][]iapservice.TunnelDestGroup    // projectID -> groups
	LootMap                 map[string]map[string]*internal.LootFile   // projectID -> loot files
	mu                      sync.Mutex
}

type IAPOutput struct {
	Table []internal.TableFile
	Loot  []internal.LootFile
}

func (o IAPOutput) TableFiles() []internal.TableFile { return o.Table }
func (o IAPOutput) LootFiles() []internal.LootFile   { return o.Loot }

func runGCPIAPCommand(cmd *cobra.Command, args []string) {
	cmdCtx, err := gcpinternal.InitializeCommandContext(cmd, globals.GCP_IAP_MODULE_NAME)
	if err != nil {
		return
	}

	module := &IAPModule{
		BaseGCPModule:           gcpinternal.NewBaseGCPModule(cmdCtx),
		ProjectTunnelDestGroups: make(map[string][]iapservice.TunnelDestGroup),
		LootMap:                 make(map[string]map[string]*internal.LootFile),
	}
	module.Execute(cmdCtx.Ctx, cmdCtx.Logger)
}

func (m *IAPModule) getAllTunnelDestGroups() []iapservice.TunnelDestGroup {
	var all []iapservice.TunnelDestGroup
	for _, groups := range m.ProjectTunnelDestGroups {
		all = append(all, groups...)
	}
	return all
}

func (m *IAPModule) Execute(ctx context.Context, logger internal.Logger) {
	m.RunProjectEnumeration(ctx, logger, m.ProjectIDs, globals.GCP_IAP_MODULE_NAME, m.processProject)

	allGroups := m.getAllTunnelDestGroups()
	if len(allGroups) == 0 {
		logger.InfoM("No IAP tunnel destination groups found", globals.GCP_IAP_MODULE_NAME)
		return
	}

	logger.SuccessM(fmt.Sprintf("Found %d IAP tunnel destination group(s)",
		len(allGroups)), globals.GCP_IAP_MODULE_NAME)
	m.writeOutput(ctx, logger)
}

func (m *IAPModule) processProject(ctx context.Context, projectID string, logger internal.Logger) {
	if globals.GCP_VERBOSITY >= globals.GCP_VERBOSE_ERRORS {
		logger.InfoM(fmt.Sprintf("Enumerating IAP in project: %s", projectID), globals.GCP_IAP_MODULE_NAME)
	}

	m.mu.Lock()
	// Initialize loot for this project
	if m.LootMap[projectID] == nil {
		m.LootMap[projectID] = make(map[string]*internal.LootFile)
		m.LootMap[projectID]["iap-commands"] = &internal.LootFile{
			Name:     "iap-commands",
			Contents: "# IAP Commands\n# Generated by CloudFox\n# WARNING: Only use with proper authorization\n\n",
		}
	}
	m.mu.Unlock()

	svc := iapservice.New()

	// Get tunnel destination groups
	groups, err := svc.ListTunnelDestGroups(projectID)
	if err != nil {
		m.CommandCounter.Error++
		gcpinternal.HandleGCPError(err, logger, globals.GCP_IAP_MODULE_NAME,
			fmt.Sprintf("Could not enumerate IAP tunnel groups in project %s", projectID))
	} else {
		m.mu.Lock()
		m.ProjectTunnelDestGroups[projectID] = groups
		for _, group := range groups {
			m.addToLoot(projectID, group)
		}
		m.mu.Unlock()
	}
}

func (m *IAPModule) addToLoot(projectID string, group iapservice.TunnelDestGroup) {
	lootFile := m.LootMap[projectID]["iap-commands"]
	if lootFile == nil {
		return
	}
	lootFile.Contents += fmt.Sprintf(
		"# =============================================================================\n"+
			"# TUNNEL DESTINATION GROUP: %s\n"+
			"# =============================================================================\n"+
			"# Project: %s\n"+
			"# Region: %s\n"+
			"# CIDRs: %s\n"+
			"# FQDNs: %s\n",
		group.Name, group.ProjectID, group.Region,
		strings.Join(group.CIDRs, ", "),
		strings.Join(group.FQDNs, ", "),
	)

	lootFile.Contents += fmt.Sprintf(`
# === ENUMERATION COMMANDS ===

# Describe tunnel destination group:
gcloud iap tcp dest-groups describe %s --region=%s --project=%s

# List IAM policy for tunnel destination group:
gcloud iap tcp dest-groups get-iam-policy %s --region=%s --project=%s

# List all IAP tunnel resources in project:
gcloud iap tcp dest-groups list --region=%s --project=%s

# Check who can use IAP tunnels in this project:
gcloud projects get-iam-policy %s --format=json | jq '.bindings[] | select(.role | contains("iap.tunnelResourceAccessor"))'

`, group.Name, group.Region, group.ProjectID,
		group.Name, group.Region, group.ProjectID,
		group.Region, group.ProjectID,
		group.ProjectID,
	)

	// === EXPLOIT COMMANDS - IAP Tunnel ===
	lootFile.Contents += "# === EXPLOIT COMMANDS ===\n\n"

	// SSH through IAP tunnel
	for _, cidr := range group.CIDRs {
		lootFile.Contents += fmt.Sprintf(
			"# Start IAP TCP tunnel to hosts in CIDR %s:\n"+
				"gcloud compute start-iap-tunnel INSTANCE_NAME 22 --local-host-port=localhost:2222 --zone=ZONE --project=%s\n"+
				"ssh -p 2222 localhost\n\n",
			cidr, group.ProjectID,
		)
	}

	for _, fqdn := range group.FQDNs {
		lootFile.Contents += fmt.Sprintf(
			"# Start IAP TCP tunnel to %s:\n"+
				"gcloud compute start-iap-tunnel INSTANCE_NAME 22 --local-host-port=localhost:2222 --zone=ZONE --project=%s\n"+
				"ssh -p 2222 localhost\n\n",
			fqdn, group.ProjectID,
		)
	}

	lootFile.Contents += fmt.Sprintf(
		"# SSH to a compute instance through IAP (direct):\n"+
			"gcloud compute ssh INSTANCE_NAME --tunnel-through-iap --zone=ZONE --project=%s\n\n"+
			"# Forward RDP through IAP (Windows instances):\n"+
			"gcloud compute start-iap-tunnel INSTANCE_NAME 3389 --local-host-port=localhost:3389 --zone=ZONE --project=%s\n\n"+
			"# Forward arbitrary port through IAP:\n"+
			"gcloud compute start-iap-tunnel INSTANCE_NAME 8080 --local-host-port=localhost:8080 --zone=ZONE --project=%s\n\n"+
			"# Port scan through IAP tunnel (test internal connectivity):\n"+
			"for PORT in 22 80 443 3306 5432 8080 8443; do\n"+
			"  gcloud compute start-iap-tunnel INSTANCE_NAME $PORT --local-host-port=localhost:$PORT --zone=ZONE --project=%s &\n"+
			"  sleep 1 && nc -z localhost $PORT 2>/dev/null && echo \"Port $PORT is open\" || echo \"Port $PORT is closed\"\n"+
			"  kill %%1 2>/dev/null\n"+
			"done\n\n",
		group.ProjectID,
		group.ProjectID,
		group.ProjectID,
		group.ProjectID,
	)
}

func (m *IAPModule) writeOutput(ctx context.Context, logger internal.Logger) {
	if m.Hierarchy != nil && !m.FlatOutput {
		m.writeHierarchicalOutput(ctx, logger)
	} else {
		m.writeFlatOutput(ctx, logger)
	}
}

func (m *IAPModule) getHeader() []string {
	return []string{
		"Project",
		"Name",
		"Region",
		"CIDRs",
		"FQDNs",
		"IAM Binding Role",
		"IAM Binding Principal",
	}
}

func (m *IAPModule) groupsToTableBody(groups []iapservice.TunnelDestGroup) [][]string {
	var body [][]string
	for _, group := range groups {
		cidrs := strings.Join(group.CIDRs, ", ")
		if cidrs == "" {
			cidrs = "-"
		}
		fqdns := strings.Join(group.FQDNs, ", ")
		if fqdns == "" {
			fqdns = "-"
		}

		if len(group.IAMBindings) > 0 {
			for _, binding := range group.IAMBindings {
				body = append(body, []string{
					m.GetProjectName(group.ProjectID),
					group.Name,
					group.Region,
					cidrs,
					fqdns,
					binding.Role,
					binding.Member,
				})
			}
		} else {
			body = append(body, []string{
				m.GetProjectName(group.ProjectID),
				group.Name,
				group.Region,
				cidrs,
				fqdns,
				"-",
				"-",
			})
		}
	}
	return body
}

func (m *IAPModule) buildTablesForProject(projectID string) []internal.TableFile {
	var tableFiles []internal.TableFile

	if groups, ok := m.ProjectTunnelDestGroups[projectID]; ok && len(groups) > 0 {
		tableFiles = append(tableFiles, internal.TableFile{
			Name:   "iap-tunnel-groups",
			Header: m.getHeader(),
			Body:   m.groupsToTableBody(groups),
		})
	}

	return tableFiles
}

func (m *IAPModule) writeHierarchicalOutput(ctx context.Context, logger internal.Logger) {
	outputData := internal.HierarchicalOutputData{
		OrgLevelData:     make(map[string]internal.CloudfoxOutput),
		ProjectLevelData: make(map[string]internal.CloudfoxOutput),
	}

	for projectID := range m.ProjectTunnelDestGroups {
		tableFiles := m.buildTablesForProject(projectID)

		var lootFiles []internal.LootFile
		if projectLoot, ok := m.LootMap[projectID]; ok {
			for _, loot := range projectLoot {
				if loot != nil && loot.Contents != "" && !strings.HasSuffix(loot.Contents, "# WARNING: Only use with proper authorization\n\n") {
					lootFiles = append(lootFiles, *loot)
				}
			}
		}

		outputData.ProjectLevelData[projectID] = IAPOutput{Table: tableFiles, Loot: lootFiles}
	}

	pathBuilder := m.BuildPathBuilder()

	err := internal.HandleHierarchicalOutputSmart("gcp", m.Format, m.Verbosity, m.WrapTable, pathBuilder, outputData)
	if err != nil {
		logger.ErrorM(fmt.Sprintf("Error writing hierarchical output: %v", err), globals.GCP_IAP_MODULE_NAME)
	}
}

func (m *IAPModule) writeFlatOutput(ctx context.Context, logger internal.Logger) {
	allGroups := m.getAllTunnelDestGroups()

	var tables []internal.TableFile

	if len(allGroups) > 0 {
		tables = append(tables, internal.TableFile{
			Name:   "iap-tunnel-groups",
			Header: m.getHeader(),
			Body:   m.groupsToTableBody(allGroups),
		})
	}

	var lootFiles []internal.LootFile
	for _, projectLoot := range m.LootMap {
		for _, loot := range projectLoot {
			if loot != nil && loot.Contents != "" && !strings.HasSuffix(loot.Contents, "# WARNING: Only use with proper authorization\n\n") {
				lootFiles = append(lootFiles, *loot)
			}
		}
	}

	output := IAPOutput{Table: tables, Loot: lootFiles}

	scopeNames := make([]string, len(m.ProjectIDs))
	for i, id := range m.ProjectIDs {
		scopeNames[i] = m.GetProjectName(id)
	}

	err := internal.HandleOutputSmart("gcp", m.Format, m.OutputDirectory, m.Verbosity, m.WrapTable,
		"project", m.ProjectIDs, scopeNames, m.Account, output)
	if err != nil {
		logger.ErrorM(fmt.Sprintf("Error writing output: %v", err), globals.GCP_IAP_MODULE_NAME)
	}
}
