package commands

import (
	"context"
	"fmt"
	"strings"
	"sync"

	"github.com/BishopFox/cloudfox/gcp/shared"

	diagramservice "github.com/BishopFox/cloudfox/gcp/services/diagramService"
	loadbalancerservice "github.com/BishopFox/cloudfox/gcp/services/loadbalancerService"
	"github.com/BishopFox/cloudfox/globals"
	"github.com/BishopFox/cloudfox/internal"
	gcpinternal "github.com/BishopFox/cloudfox/internal/gcp"
	"github.com/spf13/cobra"
)

var GCPLoadBalancersCommand = &cobra.Command{
	Use:     globals.GCP_LOADBALANCERS_MODULE_NAME,
	Aliases: []string{"lb", "lbs"},
	Short:   "Enumerate Load Balancers",
	Long: `Enumerate Load Balancers and related configurations.

Features:
- Lists all forwarding rules (global and regional)
- Shows backend services and health checks
- Analyzes SSL policies for weak configurations
- Identifies external vs internal load balancers
- Checks for Cloud Armor security policies`,
	Run: runGCPLoadBalancersCommand,
}

type LoadBalancersModule struct {
	gcpinternal.BaseGCPModule
	ProjectLoadBalancers   map[string][]loadbalancerservice.LoadBalancerInfo   // projectID -> load balancers
	ProjectSSLPolicies     map[string][]loadbalancerservice.SSLPolicyInfo      // projectID -> SSL policies
	ProjectBackendServices map[string][]loadbalancerservice.BackendServiceInfo // projectID -> backend services
	LootMap                map[string]map[string]*internal.LootFile            // projectID -> loot files
	mu                     sync.Mutex
}

type LoadBalancersOutput struct {
	Table []internal.TableFile
	Loot  []internal.LootFile
}

func (o LoadBalancersOutput) TableFiles() []internal.TableFile { return o.Table }
func (o LoadBalancersOutput) LootFiles() []internal.LootFile   { return o.Loot }

func runGCPLoadBalancersCommand(cmd *cobra.Command, args []string) {
	cmdCtx, err := gcpinternal.InitializeCommandContext(cmd, globals.GCP_LOADBALANCERS_MODULE_NAME)
	if err != nil {
		return
	}

	module := &LoadBalancersModule{
		BaseGCPModule:          gcpinternal.NewBaseGCPModule(cmdCtx),
		ProjectLoadBalancers:   make(map[string][]loadbalancerservice.LoadBalancerInfo),
		ProjectSSLPolicies:     make(map[string][]loadbalancerservice.SSLPolicyInfo),
		ProjectBackendServices: make(map[string][]loadbalancerservice.BackendServiceInfo),
		LootMap:                make(map[string]map[string]*internal.LootFile),
	}
	module.Execute(cmdCtx.Ctx, cmdCtx.Logger)
}

func (m *LoadBalancersModule) Execute(ctx context.Context, logger internal.Logger) {
	m.RunProjectEnumeration(ctx, logger, m.ProjectIDs, globals.GCP_LOADBALANCERS_MODULE_NAME, m.processProject)

	allLoadBalancers := m.getAllLoadBalancers()
	allSSLPolicies := m.getAllSSLPolicies()
	allBackendServices := m.getAllBackendServices()

	if len(allLoadBalancers) == 0 {
		logger.InfoM("No load balancers found", globals.GCP_LOADBALANCERS_MODULE_NAME)
		return
	}

	externalCount := 0
	for _, lb := range allLoadBalancers {
		if lb.Scheme == "EXTERNAL" {
			externalCount++
		}
	}

	logger.SuccessM(fmt.Sprintf("Found %d load balancer(s) (%d external), %d SSL policies, %d backend services",
		len(allLoadBalancers), externalCount, len(allSSLPolicies), len(allBackendServices)), globals.GCP_LOADBALANCERS_MODULE_NAME)
	m.writeOutput(ctx, logger)
}

func (m *LoadBalancersModule) getAllLoadBalancers() []loadbalancerservice.LoadBalancerInfo {
	var all []loadbalancerservice.LoadBalancerInfo
	for _, lbs := range m.ProjectLoadBalancers {
		all = append(all, lbs...)
	}
	return all
}

func (m *LoadBalancersModule) getAllSSLPolicies() []loadbalancerservice.SSLPolicyInfo {
	var all []loadbalancerservice.SSLPolicyInfo
	for _, policies := range m.ProjectSSLPolicies {
		all = append(all, policies...)
	}
	return all
}

func (m *LoadBalancersModule) getAllBackendServices() []loadbalancerservice.BackendServiceInfo {
	var all []loadbalancerservice.BackendServiceInfo
	for _, services := range m.ProjectBackendServices {
		all = append(all, services...)
	}
	return all
}

func (m *LoadBalancersModule) processProject(ctx context.Context, projectID string, logger internal.Logger) {
	if globals.GCP_VERBOSITY >= globals.GCP_VERBOSE_ERRORS {
		logger.InfoM(fmt.Sprintf("Enumerating load balancers in project: %s", projectID), globals.GCP_LOADBALANCERS_MODULE_NAME)
	}

	svc := loadbalancerservice.New()

	m.mu.Lock()
	// Initialize loot for this project
	if m.LootMap[projectID] == nil {
		m.LootMap[projectID] = make(map[string]*internal.LootFile)
		m.LootMap[projectID]["loadbalancers-commands"] = &internal.LootFile{
			Name:     "loadbalancers-commands",
			Contents: "# Load Balancer Commands\n# Generated by CloudFox\n# WARNING: Only use with proper authorization\n\n",
		}
	}
	m.mu.Unlock()

	// Get load balancers
	lbs, err := svc.ListLoadBalancers(projectID)
	if err != nil {
		m.CommandCounter.Error++
		gcpinternal.HandleGCPError(err, logger, globals.GCP_LOADBALANCERS_MODULE_NAME,
			fmt.Sprintf("Could not list load balancers in project %s", projectID))
	} else {
		m.mu.Lock()
		m.ProjectLoadBalancers[projectID] = lbs
		for _, lb := range lbs {
			m.addToLoot(projectID, lb)
		}
		m.mu.Unlock()
	}

	// Get SSL policies
	sslPolicies, err := svc.ListSSLPolicies(projectID)
	if err != nil {
		m.CommandCounter.Error++
		gcpinternal.HandleGCPError(err, logger, globals.GCP_LOADBALANCERS_MODULE_NAME,
			fmt.Sprintf("Could not list SSL policies in project %s", projectID))
	} else {
		m.mu.Lock()
		m.ProjectSSLPolicies[projectID] = sslPolicies
		m.mu.Unlock()
	}

	// Get backend services
	backends, err := svc.ListBackendServices(projectID)
	if err != nil {
		m.CommandCounter.Error++
		gcpinternal.HandleGCPError(err, logger, globals.GCP_LOADBALANCERS_MODULE_NAME,
			fmt.Sprintf("Could not list backend services in project %s", projectID))
	} else {
		m.mu.Lock()
		m.ProjectBackendServices[projectID] = backends
		m.mu.Unlock()
	}
}

func (m *LoadBalancersModule) addToLoot(projectID string, lb loadbalancerservice.LoadBalancerInfo) {
	lootFile := m.LootMap[projectID]["loadbalancers-commands"]
	if lootFile == nil {
		return
	}
	lootFile.Contents += fmt.Sprintf(
		"# =============================================================================\n"+
			"# LOAD BALANCER: %s\n"+
			"# =============================================================================\n"+
			"# Project: %s\n"+
			"# Type: %s, Scheme: %s, IP: %s, Port: %s\n\n",
		lb.Name, lb.ProjectID, lb.Type, lb.Scheme, lb.IPAddress, lb.Port)

	lootFile.Contents += "# === ENUMERATION COMMANDS ===\n\n"

	// Describe forwarding rule
	if lb.Region == "global" {
		lootFile.Contents += fmt.Sprintf(
			"# Describe global forwarding rule:\n"+
				"gcloud compute forwarding-rules describe %s --global --project=%s\n\n",
			lb.Name, lb.ProjectID)
	} else {
		lootFile.Contents += fmt.Sprintf(
			"# Describe regional forwarding rule:\n"+
				"gcloud compute forwarding-rules describe %s --region=%s --project=%s\n\n",
			lb.Name, lb.Region, lb.ProjectID)
	}

	// Backend service commands
	for _, backend := range lb.BackendServices {
		lootFile.Contents += fmt.Sprintf(
			"# Describe backend service:\n"+
				"gcloud compute backend-services describe %s --global --project=%s\n\n",
			backend, lb.ProjectID)
	}
}

func (m *LoadBalancersModule) writeOutput(ctx context.Context, logger internal.Logger) {
	// Generate ASCII diagram and add to loot
	diagram := m.generateLoadBalancerDiagram()
	if diagram != "" {
		// Add diagram to the first project's loot
		for projectID := range m.LootMap {
			if m.LootMap[projectID] == nil {
				m.LootMap[projectID] = make(map[string]*internal.LootFile)
			}
			m.LootMap[projectID]["loadbalancers-diagram"] = &internal.LootFile{
				Name:     "loadbalancers-diagram",
				Contents: diagram,
			}
			break // Only add once for flat output
		}

		// For hierarchical output, add to all projects
		if m.Hierarchy != nil && !m.FlatOutput {
			for projectID := range m.LootMap {
				if m.LootMap[projectID] == nil {
					m.LootMap[projectID] = make(map[string]*internal.LootFile)
				}
				m.LootMap[projectID]["loadbalancers-diagram"] = &internal.LootFile{
					Name:     "loadbalancers-diagram",
					Contents: diagram,
				}
			}
		}
	}

	if m.Hierarchy != nil && !m.FlatOutput {
		m.writeHierarchicalOutput(ctx, logger)
	} else {
		m.writeFlatOutput(ctx, logger)
	}
}

// ------------------------------
// Diagram Generation
// ------------------------------

// generateLoadBalancerDiagram creates an ASCII visualization of load balancer architecture
func (m *LoadBalancersModule) generateLoadBalancerDiagram() string {
	allLBs := m.getAllLoadBalancers()
	if len(allLBs) == 0 {
		return ""
	}

	// Build a map of backend service name -> actual backends (instance groups, NEGs)
	backendDetailsMap := make(map[string][]string)
	for _, backends := range m.ProjectBackendServices {
		for _, be := range backends {
			if len(be.Backends) > 0 {
				backendDetailsMap[be.Name] = be.Backends
			}
		}
	}

	// Convert to diagram service types
	diagramLBs := make([]diagramservice.LoadBalancerInfo, 0, len(allLBs))
	for _, lb := range allLBs {
		// Build backend details for this LB
		lbBackendDetails := make(map[string][]string)
		for _, beSvc := range lb.BackendServices {
			if targets, ok := backendDetailsMap[beSvc]; ok {
				lbBackendDetails[beSvc] = targets
			}
		}

		diagramLBs = append(diagramLBs, diagramservice.LoadBalancerInfo{
			Name:            lb.Name,
			Type:            lb.Type,
			Scheme:          lb.Scheme,
			IPAddress:       lb.IPAddress,
			Port:            lb.Port,
			Region:          lb.Region,
			BackendServices: lb.BackendServices,
			SecurityPolicy:  lb.SecurityPolicy,
			BackendDetails:  lbBackendDetails,
		})
	}

	// Determine project ID for header (use first project if multiple)
	projectID := ""
	if len(m.ProjectIDs) == 1 {
		projectID = m.ProjectIDs[0]
	}

	return diagramservice.DrawLoadBalancerDiagram(diagramLBs, projectID, 90)
}

func (m *LoadBalancersModule) getLBHeader() []string {
	return []string{"Project", "Name", "Type", "Scheme", "Region", "IP Address", "Port", "Backend Services", "Security Policy"}
}

func (m *LoadBalancersModule) getSSLHeader() []string {
	return []string{"Project", "Name", "Min TLS Version", "Profile", "Custom Features"}
}

func (m *LoadBalancersModule) getBackendHeader() []string {
	return []string{"Project", "Name", "Protocol", "Port", "Security Policy", "CDN Enabled", "Health Check", "Session Affinity", "Backends"}
}

func (m *LoadBalancersModule) lbsToTableBody(lbs []loadbalancerservice.LoadBalancerInfo) [][]string {
	var body [][]string
	for _, lb := range lbs {
		backends := "-"
		if len(lb.BackendServices) > 0 {
			backends = strings.Join(lb.BackendServices, ", ")
		}
		secPolicy := "-"
		if lb.SecurityPolicy != "" {
			secPolicy = lb.SecurityPolicy
		}
		body = append(body, []string{
			m.GetProjectName(lb.ProjectID),
			lb.Name,
			lb.Type,
			lb.Scheme,
			lb.Region,
			lb.IPAddress,
			lb.Port,
			backends,
			secPolicy,
		})
	}
	return body
}

func (m *LoadBalancersModule) sslPoliciesToTableBody(policies []loadbalancerservice.SSLPolicyInfo) [][]string {
	var body [][]string
	for _, policy := range policies {
		customFeatures := "-"
		if len(policy.CustomFeatures) > 0 {
			customFeatures = strings.Join(policy.CustomFeatures, ", ")
		}
		body = append(body, []string{
			m.GetProjectName(policy.ProjectID),
			policy.Name,
			policy.MinTLSVersion,
			policy.Profile,
			customFeatures,
		})
	}
	return body
}

func (m *LoadBalancersModule) backendServicesToTableBody(services []loadbalancerservice.BackendServiceInfo) [][]string {
	var body [][]string
	for _, be := range services {
		secPolicy := "-"
		if be.SecurityPolicy != "" {
			secPolicy = be.SecurityPolicy
		}
		healthCheck := "-"
		if be.HealthCheck != "" {
			healthCheck = be.HealthCheck
		}
		sessionAffinity := "-"
		if be.SessionAffinity != "" {
			sessionAffinity = be.SessionAffinity
		}
		backends := "-"
		if len(be.Backends) > 0 {
			backends = strings.Join(be.Backends, ", ")
		}
		body = append(body, []string{
			m.GetProjectName(be.ProjectID),
			be.Name,
			be.Protocol,
			fmt.Sprintf("%d", be.Port),
			secPolicy,
			shared.BoolToYesNo(be.EnableCDN),
			healthCheck,
			sessionAffinity,
			backends,
		})
	}
	return body
}

func (m *LoadBalancersModule) buildTablesForProject(projectID string) []internal.TableFile {
	var tableFiles []internal.TableFile

	if lbs, ok := m.ProjectLoadBalancers[projectID]; ok && len(lbs) > 0 {
		tableFiles = append(tableFiles, internal.TableFile{
			Name:   "load-balancers-frontends",
			Header: m.getLBHeader(),
			Body:   m.lbsToTableBody(lbs),
		})
	}

	if policies, ok := m.ProjectSSLPolicies[projectID]; ok && len(policies) > 0 {
		tableFiles = append(tableFiles, internal.TableFile{
			Name:   "ssl-policies",
			Header: m.getSSLHeader(),
			Body:   m.sslPoliciesToTableBody(policies),
		})
	}

	if services, ok := m.ProjectBackendServices[projectID]; ok && len(services) > 0 {
		tableFiles = append(tableFiles, internal.TableFile{
			Name:   "load-balancers-backend-services",
			Header: m.getBackendHeader(),
			Body:   m.backendServicesToTableBody(services),
		})
	}

	return tableFiles
}

func (m *LoadBalancersModule) writeHierarchicalOutput(ctx context.Context, logger internal.Logger) {
	outputData := internal.HierarchicalOutputData{
		OrgLevelData:     make(map[string]internal.CloudfoxOutput),
		ProjectLevelData: make(map[string]internal.CloudfoxOutput),
	}

	// Get all project IDs that have data
	projectIDs := make(map[string]bool)
	for projectID := range m.ProjectLoadBalancers {
		projectIDs[projectID] = true
	}
	for projectID := range m.ProjectSSLPolicies {
		projectIDs[projectID] = true
	}
	for projectID := range m.ProjectBackendServices {
		projectIDs[projectID] = true
	}

	for projectID := range projectIDs {
		tableFiles := m.buildTablesForProject(projectID)

		var lootFiles []internal.LootFile
		if projectLoot, ok := m.LootMap[projectID]; ok {
			for _, loot := range projectLoot {
				if loot != nil && loot.Contents != "" && !strings.HasSuffix(loot.Contents, "# WARNING: Only use with proper authorization\n\n") {
					lootFiles = append(lootFiles, *loot)
				}
			}
		}

		outputData.ProjectLevelData[projectID] = LoadBalancersOutput{Table: tableFiles, Loot: lootFiles}
	}

	pathBuilder := m.BuildPathBuilder()

	err := internal.HandleHierarchicalOutputSmart("gcp", m.Format, m.Verbosity, m.WrapTable, pathBuilder, outputData)
	if err != nil {
		logger.ErrorM(fmt.Sprintf("Error writing hierarchical output: %v", err), globals.GCP_LOADBALANCERS_MODULE_NAME)
	}
}

func (m *LoadBalancersModule) writeFlatOutput(ctx context.Context, logger internal.Logger) {
	allLBs := m.getAllLoadBalancers()
	allSSL := m.getAllSSLPolicies()
	allBackends := m.getAllBackendServices()

	var tables []internal.TableFile

	if len(allLBs) > 0 {
		tables = append(tables, internal.TableFile{
			Name:   "load-balancers-frontends",
			Header: m.getLBHeader(),
			Body:   m.lbsToTableBody(allLBs),
		})
	}

	if len(allSSL) > 0 {
		tables = append(tables, internal.TableFile{
			Name:   "ssl-policies",
			Header: m.getSSLHeader(),
			Body:   m.sslPoliciesToTableBody(allSSL),
		})
	}

	if len(allBackends) > 0 {
		tables = append(tables, internal.TableFile{
			Name:   "load-balancers-backend-services",
			Header: m.getBackendHeader(),
			Body:   m.backendServicesToTableBody(allBackends),
		})
	}

	var lootFiles []internal.LootFile
	for _, projectLoot := range m.LootMap {
		for _, loot := range projectLoot {
			if loot != nil && loot.Contents != "" && !strings.HasSuffix(loot.Contents, "# WARNING: Only use with proper authorization\n\n") {
				lootFiles = append(lootFiles, *loot)
			}
		}
	}

	output := LoadBalancersOutput{Table: tables, Loot: lootFiles}

	scopeNames := make([]string, len(m.ProjectIDs))
	for i, id := range m.ProjectIDs {
		scopeNames[i] = m.GetProjectName(id)
	}

	err := internal.HandleOutputSmart("gcp", m.Format, m.OutputDirectory, m.Verbosity, m.WrapTable,
		"project", m.ProjectIDs, scopeNames, m.Account, output)
	if err != nil {
		logger.ErrorM(fmt.Sprintf("Error writing output: %v", err), globals.GCP_LOADBALANCERS_MODULE_NAME)
	}
}
