package commands

import (
	"github.com/BishopFox/cloudfox/gcp/shared"
	"context"
	"fmt"
	"strings"
	"sync"

	memorystoreservice "github.com/BishopFox/cloudfox/gcp/services/memorystoreService"
	"github.com/BishopFox/cloudfox/globals"
	"github.com/BishopFox/cloudfox/internal"
	gcpinternal "github.com/BishopFox/cloudfox/internal/gcp"
	"github.com/spf13/cobra"
)

var GCPMemorystoreCommand = &cobra.Command{
	Use:     globals.GCP_MEMORYSTORE_MODULE_NAME,
	Aliases: []string{"redis", "cache"},
	Short:   "Enumerate Memorystore (Redis) instances",
	Long: `Enumerate Memorystore for Redis instances with security analysis.

Features:
- Lists all Redis instances
- Shows authentication and encryption status
- Identifies network configuration
- Detects security misconfigurations`,
	Run: runGCPMemorystoreCommand,
}

type MemorystoreModule struct {
	gcpinternal.BaseGCPModule
	ProjectInstances map[string][]memorystoreservice.RedisInstanceInfo // projectID -> instances
	LootMap          map[string]map[string]*internal.LootFile          // projectID -> loot files
	mu               sync.Mutex
}

type MemorystoreOutput struct {
	Table []internal.TableFile
	Loot  []internal.LootFile
}

func (o MemorystoreOutput) TableFiles() []internal.TableFile { return o.Table }
func (o MemorystoreOutput) LootFiles() []internal.LootFile   { return o.Loot }

func runGCPMemorystoreCommand(cmd *cobra.Command, args []string) {
	cmdCtx, err := gcpinternal.InitializeCommandContext(cmd, globals.GCP_MEMORYSTORE_MODULE_NAME)
	if err != nil {
		return
	}

	module := &MemorystoreModule{
		BaseGCPModule:    gcpinternal.NewBaseGCPModule(cmdCtx),
		ProjectInstances: make(map[string][]memorystoreservice.RedisInstanceInfo),
		LootMap:          make(map[string]map[string]*internal.LootFile),
	}
	module.Execute(cmdCtx.Ctx, cmdCtx.Logger)
}

func (m *MemorystoreModule) Execute(ctx context.Context, logger internal.Logger) {
	m.RunProjectEnumeration(ctx, logger, m.ProjectIDs, globals.GCP_MEMORYSTORE_MODULE_NAME, m.processProject)

	allInstances := m.getAllInstances()
	if len(allInstances) == 0 {
		logger.InfoM("No Memorystore instances found", globals.GCP_MEMORYSTORE_MODULE_NAME)
		return
	}

	noAuth := 0
	for _, instance := range allInstances {
		if !instance.AuthEnabled {
			noAuth++
		}
	}

	logger.SuccessM(fmt.Sprintf("Found %d Redis instance(s) (%d without auth)",
		len(allInstances), noAuth), globals.GCP_MEMORYSTORE_MODULE_NAME)

	m.writeOutput(ctx, logger)
}

func (m *MemorystoreModule) getAllInstances() []memorystoreservice.RedisInstanceInfo {
	var all []memorystoreservice.RedisInstanceInfo
	for _, instances := range m.ProjectInstances {
		all = append(all, instances...)
	}
	return all
}

func (m *MemorystoreModule) processProject(ctx context.Context, projectID string, logger internal.Logger) {
	if globals.GCP_VERBOSITY >= globals.GCP_VERBOSE_ERRORS {
		logger.InfoM(fmt.Sprintf("Enumerating Memorystore in project: %s", projectID), globals.GCP_MEMORYSTORE_MODULE_NAME)
	}

	svc := memorystoreservice.New()
	instances, err := svc.ListRedisInstances(projectID)
	if err != nil {
		m.CommandCounter.Error++
		gcpinternal.HandleGCPError(err, logger, globals.GCP_MEMORYSTORE_MODULE_NAME,
			fmt.Sprintf("Could not list Redis instances in project %s", projectID))
		return
	}

	m.mu.Lock()
	m.ProjectInstances[projectID] = instances

	// Initialize loot for this project
	if m.LootMap[projectID] == nil {
		m.LootMap[projectID] = make(map[string]*internal.LootFile)
		m.LootMap[projectID]["memorystore-commands"] = &internal.LootFile{
			Name:     "memorystore-commands",
			Contents: "# Memorystore Commands\n# Generated by CloudFox\n# WARNING: Only use with proper authorization\n\n",
		}
	}

	for _, instance := range instances {
		m.addInstanceToLoot(projectID, instance)
	}
	m.mu.Unlock()
}

func (m *MemorystoreModule) addInstanceToLoot(projectID string, instance memorystoreservice.RedisInstanceInfo) {
	lootFile := m.LootMap[projectID]["memorystore-commands"]
	if lootFile == nil {
		return
	}
	lootFile.Contents += fmt.Sprintf(
		"# =============================================================================\n"+
			"# MEMORYSTORE: %s\n"+
			"# =============================================================================\n"+
			"# Project: %s, Location: %s\n"+
			"# Host: %s:%d\n"+
			"# Auth: %v, Encryption: %s\n\n",
		instance.Name,
		instance.ProjectID, instance.Location,
		instance.Host, instance.Port,
		instance.AuthEnabled, instance.TransitEncryption,
	)

	// gcloud commands
	lootFile.Contents += fmt.Sprintf(
		"# === ENUMERATION COMMANDS ===\n\n"+
			"# Describe instance:\n"+
			"gcloud redis instances describe %s --region=%s --project=%s\n\n",
		instance.Name, instance.Location, instance.ProjectID,
	)

	// Auth string command (if auth enabled)
	if instance.AuthEnabled {
		lootFile.Contents += fmt.Sprintf(
			"# Get auth string:\n"+
				"gcloud redis instances get-auth-string %s --region=%s --project=%s\n\n",
			instance.Name, instance.Location, instance.ProjectID,
		)
	}

	// Redis CLI connection command
	lootFile.Contents += "# === EXPLOIT COMMANDS ===\n\n"
	authStr := ""
	if instance.AuthEnabled {
		authStr = " -a $(gcloud redis instances get-auth-string " + instance.Name +
			" --region=" + instance.Location + " --project=" + instance.ProjectID +
			" --format='value(authString)')"
	}
	lootFile.Contents += fmt.Sprintf(
		"# Connect to Redis (from a VM in the same VPC):\n"+
			"redis-cli -h %s -p %d%s\n\n",
		instance.Host, instance.Port, authStr,
	)
}

// extractNetworkName extracts the network name from the full resource path
func extractNetworkName(network string) string {
	if network == "" {
		return "-"
	}
	parts := strings.Split(network, "/")
	if len(parts) > 0 {
		return parts[len(parts)-1]
	}
	return network
}

func (m *MemorystoreModule) writeOutput(ctx context.Context, logger internal.Logger) {
	if m.Hierarchy != nil && !m.FlatOutput {
		m.writeHierarchicalOutput(ctx, logger)
	} else {
		m.writeFlatOutput(ctx, logger)
	}
}

func (m *MemorystoreModule) getTableHeader() []string {
	return []string{
		"Project Name",
		"Project ID",
		"Name",
		"Location",
		"Tier",
		"Memory (GB)",
		"Version",
		"Host:Port",
		"Auth Enabled",
		"Transit Encryption",
		"State",
		"Network",
		"Connect Mode",
	}
}

func (m *MemorystoreModule) instancesToTableBody(instances []memorystoreservice.RedisInstanceInfo) [][]string {
	var body [][]string
	for _, instance := range instances {
		transitEncryption := instance.TransitEncryption
		if transitEncryption == "" {
			transitEncryption = "DISABLED"
		}
		body = append(body, []string{
			m.GetProjectName(instance.ProjectID),
			instance.ProjectID,
			instance.Name,
			instance.Location,
			instance.Tier,
			fmt.Sprintf("%d", instance.MemorySizeGB),
			instance.RedisVersion,
			fmt.Sprintf("%s:%d", instance.Host, instance.Port),
			shared.BoolToYesNo(instance.AuthEnabled),
			transitEncryption,
			instance.State,
			extractNetworkName(instance.AuthorizedNetwork),
			instance.ConnectMode,
		})
	}
	return body
}

func (m *MemorystoreModule) writeHierarchicalOutput(ctx context.Context, logger internal.Logger) {
	outputData := internal.HierarchicalOutputData{
		OrgLevelData:     make(map[string]internal.CloudfoxOutput),
		ProjectLevelData: make(map[string]internal.CloudfoxOutput),
	}

	for projectID, instances := range m.ProjectInstances {
		body := m.instancesToTableBody(instances)
		tableFiles := []internal.TableFile{{Name: "memorystore", Header: m.getTableHeader(), Body: body}}

		var lootFiles []internal.LootFile
		if projectLoot, ok := m.LootMap[projectID]; ok {
			for _, loot := range projectLoot {
				if loot != nil && loot.Contents != "" && !strings.HasSuffix(loot.Contents, "# WARNING: Only use with proper authorization\n\n") {
					lootFiles = append(lootFiles, *loot)
				}
			}
		}

		outputData.ProjectLevelData[projectID] = MemorystoreOutput{Table: tableFiles, Loot: lootFiles}
	}

	pathBuilder := m.BuildPathBuilder()

	err := internal.HandleHierarchicalOutputSmart("gcp", m.Format, m.Verbosity, m.WrapTable, pathBuilder, outputData)
	if err != nil {
		logger.ErrorM(fmt.Sprintf("Error writing hierarchical output: %v", err), globals.GCP_MEMORYSTORE_MODULE_NAME)
	}
}

func (m *MemorystoreModule) writeFlatOutput(ctx context.Context, logger internal.Logger) {
	allInstances := m.getAllInstances()
	body := m.instancesToTableBody(allInstances)

	var lootFiles []internal.LootFile
	for _, projectLoot := range m.LootMap {
		for _, loot := range projectLoot {
			if loot != nil && loot.Contents != "" && !strings.HasSuffix(loot.Contents, "# WARNING: Only use with proper authorization\n\n") {
				lootFiles = append(lootFiles, *loot)
			}
		}
	}

	tables := []internal.TableFile{{Name: "memorystore", Header: m.getTableHeader(), Body: body}}
	output := MemorystoreOutput{Table: tables, Loot: lootFiles}

	scopeNames := make([]string, len(m.ProjectIDs))
	for i, id := range m.ProjectIDs {
		scopeNames[i] = m.GetProjectName(id)
	}

	err := internal.HandleOutputSmart("gcp", m.Format, m.OutputDirectory, m.Verbosity, m.WrapTable,
		"project", m.ProjectIDs, scopeNames, m.Account, output)
	if err != nil {
		logger.ErrorM(fmt.Sprintf("Error writing output: %v", err), globals.GCP_MEMORYSTORE_MODULE_NAME)
	}
}
