package commands

import (
	"context"
	"fmt"
	"strings"
	"sync"

	sourcereposservice "github.com/BishopFox/cloudfox/gcp/services/sourceReposService"
	"github.com/BishopFox/cloudfox/globals"
	"github.com/BishopFox/cloudfox/internal"
	gcpinternal "github.com/BishopFox/cloudfox/internal/gcp"
	"github.com/spf13/cobra"
)

var GCPSourceReposCommand = &cobra.Command{
	Use:     globals.GCP_SOURCEREPOS_MODULE_NAME,
	Aliases: []string{"repos", "csr", "git"},
	Short:   "Enumerate Cloud Source Repositories",
	Long: `Enumerate Cloud Source Repositories for code and secrets.

Cloud Source Repositories can contain:
- Application source code
- Infrastructure as Code (Terraform, CloudFormation)
- Configuration files with hardcoded credentials
- API keys and secrets in code
- CI/CD pipeline configurations

Output:
- List of all repositories accessible
- Repository sizes and mirror configurations
- Clone commands for each repository
- Secret search commands

After cloning, search for:
- Hardcoded credentials and API keys
- Private keys and certificates
- Environment configuration files
- Database connection strings`,
	Run: runGCPSourceReposCommand,
}

// ------------------------------
// Module Struct
// ------------------------------
type SourceReposModule struct {
	gcpinternal.BaseGCPModule

	ProjectRepos map[string][]sourcereposservice.RepoInfo // projectID -> repos
	LootMap      map[string]map[string]*internal.LootFile // projectID -> loot files
	mu           sync.Mutex
}

// ------------------------------
// Output Struct
// ------------------------------
type SourceReposOutput struct {
	Table []internal.TableFile
	Loot  []internal.LootFile
}

func (o SourceReposOutput) TableFiles() []internal.TableFile { return o.Table }
func (o SourceReposOutput) LootFiles() []internal.LootFile   { return o.Loot }

// ------------------------------
// Command Entry Point
// ------------------------------
func runGCPSourceReposCommand(cmd *cobra.Command, args []string) {
	cmdCtx, err := gcpinternal.InitializeCommandContext(cmd, globals.GCP_SOURCEREPOS_MODULE_NAME)
	if err != nil {
		return
	}

	module := &SourceReposModule{
		BaseGCPModule: gcpinternal.NewBaseGCPModule(cmdCtx),
		ProjectRepos:  make(map[string][]sourcereposservice.RepoInfo),
		LootMap:       make(map[string]map[string]*internal.LootFile),
	}

	module.Execute(cmdCtx.Ctx, cmdCtx.Logger)
}

// ------------------------------
// Module Execution
// ------------------------------
func (m *SourceReposModule) Execute(ctx context.Context, logger internal.Logger) {
	m.RunProjectEnumeration(ctx, logger, m.ProjectIDs, globals.GCP_SOURCEREPOS_MODULE_NAME, m.processProject)

	allRepos := m.getAllRepos()
	if len(allRepos) == 0 {
		logger.InfoM("No Cloud Source Repositories found", globals.GCP_SOURCEREPOS_MODULE_NAME)
		return
	}

	logger.SuccessM(fmt.Sprintf("Found %d repository(ies)", len(allRepos)), globals.GCP_SOURCEREPOS_MODULE_NAME)
	logger.InfoM("[PENTEST] Clone repositories and search for secrets!", globals.GCP_SOURCEREPOS_MODULE_NAME)

	m.writeOutput(ctx, logger)
}

// getAllRepos returns all repos from all projects (for statistics)
func (m *SourceReposModule) getAllRepos() []sourcereposservice.RepoInfo {
	var all []sourcereposservice.RepoInfo
	for _, repos := range m.ProjectRepos {
		all = append(all, repos...)
	}
	return all
}

// ------------------------------
// Project Processor
// ------------------------------
func (m *SourceReposModule) processProject(ctx context.Context, projectID string, logger internal.Logger) {
	if globals.GCP_VERBOSITY >= globals.GCP_VERBOSE_ERRORS {
		logger.InfoM(fmt.Sprintf("Enumerating Cloud Source Repositories in project: %s", projectID), globals.GCP_SOURCEREPOS_MODULE_NAME)
	}

	svc := sourcereposservice.New()
	repos, err := svc.ListRepos(projectID)
	if err != nil {
		m.CommandCounter.Error++
		gcpinternal.HandleGCPError(err, logger, globals.GCP_SOURCEREPOS_MODULE_NAME,
			fmt.Sprintf("Could not list repos in project %s", projectID))
		return
	}

	m.mu.Lock()
	m.ProjectRepos[projectID] = repos

	// Initialize loot for this project
	if m.LootMap[projectID] == nil {
		m.LootMap[projectID] = make(map[string]*internal.LootFile)
		m.LootMap[projectID]["sourcerepos-commands"] = &internal.LootFile{
			Name:     "sourcerepos-commands",
			Contents: "# Cloud Source Repository Commands\n# Generated by CloudFox\n# WARNING: Only use with proper authorization\n\n",
		}
	}

	for _, repo := range repos {
		m.addRepoToLoot(projectID, repo)
	}
	m.mu.Unlock()

	if globals.GCP_VERBOSITY >= globals.GCP_VERBOSE_ERRORS {
		logger.InfoM(fmt.Sprintf("Found %d repository(ies) in project %s", len(repos), projectID), globals.GCP_SOURCEREPOS_MODULE_NAME)
	}
}

// ------------------------------
// Loot File Management
// ------------------------------
func (m *SourceReposModule) addRepoToLoot(projectID string, repo sourcereposservice.RepoInfo) {
	lootFile := m.LootMap[projectID]["sourcerepos-commands"]
	if lootFile == nil {
		return
	}

	lootFile.Contents += fmt.Sprintf(
		"# =============================================================================\n"+
			"# REPOSITORY: %s\n"+
			"# =============================================================================\n"+
			"# Project: %s\n",
		repo.Name, repo.ProjectID,
	)

	if repo.Size > 0 {
		lootFile.Contents += fmt.Sprintf("# Size: %d bytes\n", repo.Size)
	}
	if repo.MirrorConfig {
		lootFile.Contents += fmt.Sprintf("# Mirrors: %s\n", repo.MirrorURL)
	}
	if repo.PubsubConfigs > 0 {
		lootFile.Contents += fmt.Sprintf("# Pub/Sub Triggers: %d\n", repo.PubsubConfigs)
	}

	// IAM bindings summary
	if len(repo.IAMBindings) > 0 {
		lootFile.Contents += "# IAM Bindings:\n"
		for _, binding := range repo.IAMBindings {
			lootFile.Contents += fmt.Sprintf("#   %s -> %s\n", binding.Role, binding.Member)
		}
	}

	lootFile.Contents += fmt.Sprintf(
		"\n# Clone repository:\n"+
			"gcloud source repos clone %s --project=%s\n\n"+
			"# Get IAM policy:\n"+
			"gcloud source repos get-iam-policy %s --project=%s\n\n"+
			"# Search for secrets after cloning:\n"+
			"cd %s && grep -rE '(password|secret|api[_-]?key|private[_-]?key|AWS_|GOOGLE_|token)' . --include='*'\n"+
			"find . -name '*.pem' -o -name '*.key' -o -name '.env*' -o -name '*credential*' -o -name '*.tfvars'\n"+
			"grep -rE 'BEGIN (RSA |DSA |EC |OPENSSH )?PRIVATE KEY' .\n\n",
		repo.Name, repo.ProjectID,
		repo.Name, repo.ProjectID,
		repo.Name,
	)
}

// ------------------------------
// Output Generation
// ------------------------------
func (m *SourceReposModule) writeOutput(ctx context.Context, logger internal.Logger) {
	// Decide between hierarchical and flat output
	if m.Hierarchy != nil && !m.FlatOutput {
		m.writeHierarchicalOutput(ctx, logger)
	} else {
		m.writeFlatOutput(ctx, logger)
	}
}

// writeHierarchicalOutput writes output to per-project directories
func (m *SourceReposModule) writeHierarchicalOutput(ctx context.Context, logger internal.Logger) {
	header := []string{
		"Project",
		"Name",
		"Size",
		"Mirror",
		"Mirror URL",
		"Triggers",
		"IAM Binding Role",
		"IAM Binding Principal",
	}

	// Build hierarchical output data
	outputData := internal.HierarchicalOutputData{
		OrgLevelData:     make(map[string]internal.CloudfoxOutput),
		ProjectLevelData: make(map[string]internal.CloudfoxOutput),
	}

	// Build project-level outputs
	for projectID, repos := range m.ProjectRepos {
		body := m.reposToTableBody(repos)
		tables := []internal.TableFile{{
			Name:   "source-repos",
			Header: header,
			Body:   body,
		}}

		// Collect loot for this project
		var lootFiles []internal.LootFile
		if projectLoot, ok := m.LootMap[projectID]; ok {
			for _, loot := range projectLoot {
				if loot != nil && loot.Contents != "" && !strings.HasSuffix(loot.Contents, "# WARNING: Only use with proper authorization\n\n") {
					lootFiles = append(lootFiles, *loot)
				}
			}
		}

		outputData.ProjectLevelData[projectID] = SourceReposOutput{Table: tables, Loot: lootFiles}
	}

	// Create path builder using the module's hierarchy
	pathBuilder := m.BuildPathBuilder()

	// Write using hierarchical output
	err := internal.HandleHierarchicalOutputSmart(
		"gcp",
		m.Format,
		m.Verbosity,
		m.WrapTable,
		pathBuilder,
		outputData,
	)
	if err != nil {
		logger.ErrorM(fmt.Sprintf("Error writing hierarchical output: %v", err), globals.GCP_SOURCEREPOS_MODULE_NAME)
		m.CommandCounter.Error++
	}
}

// writeFlatOutput writes all output to a single directory (legacy mode)
func (m *SourceReposModule) writeFlatOutput(ctx context.Context, logger internal.Logger) {
	header := []string{
		"Project",
		"Name",
		"Size",
		"Mirror",
		"Mirror URL",
		"Triggers",
		"IAM Binding Role",
		"IAM Binding Principal",
	}

	allRepos := m.getAllRepos()
	body := m.reposToTableBody(allRepos)

	// Collect all loot files
	var lootFiles []internal.LootFile
	for _, projectLoot := range m.LootMap {
		for _, loot := range projectLoot {
			if loot != nil && loot.Contents != "" && !strings.HasSuffix(loot.Contents, "# WARNING: Only use with proper authorization\n\n") {
				lootFiles = append(lootFiles, *loot)
			}
		}
	}

	tables := []internal.TableFile{
		{
			Name:   "source-repos",
			Header: header,
			Body:   body,
		},
	}

	output := SourceReposOutput{
		Table: tables,
		Loot:  lootFiles,
	}

	scopeNames := make([]string, len(m.ProjectIDs))
	for i, id := range m.ProjectIDs {
		scopeNames[i] = m.GetProjectName(id)
	}

	err := internal.HandleOutputSmart(
		"gcp",
		m.Format,
		m.OutputDirectory,
		m.Verbosity,
		m.WrapTable,
		"project",
		m.ProjectIDs,
		scopeNames,
		m.Account,
		output,
	)
	if err != nil {
		logger.ErrorM(fmt.Sprintf("Error writing output: %v", err), globals.GCP_SOURCEREPOS_MODULE_NAME)
		m.CommandCounter.Error++
	}
}

// reposToTableBody converts repos to table rows
func (m *SourceReposModule) reposToTableBody(repos []sourcereposservice.RepoInfo) [][]string {
	var body [][]string
	for _, repo := range repos {
		sizeDisplay := "-"
		if repo.Size > 0 {
			if repo.Size > 1024*1024 {
				sizeDisplay = fmt.Sprintf("%.1f MB", float64(repo.Size)/(1024*1024))
			} else if repo.Size > 1024 {
				sizeDisplay = fmt.Sprintf("%.1f KB", float64(repo.Size)/1024)
			} else {
				sizeDisplay = fmt.Sprintf("%d B", repo.Size)
			}
		}

		mirror := "No"
		mirrorURL := "-"
		if repo.MirrorConfig {
			mirror = "Yes"
			mirrorURL = repo.MirrorURL
		}

		triggers := "-"
		if repo.PubsubConfigs > 0 {
			triggers = fmt.Sprintf("%d", repo.PubsubConfigs)
		}

		// One row per IAM binding
		if len(repo.IAMBindings) > 0 {
			for _, binding := range repo.IAMBindings {
				body = append(body, []string{
					m.GetProjectName(repo.ProjectID),
					repo.Name,
					sizeDisplay,
					mirror,
					mirrorURL,
					triggers,
					binding.Role,
					binding.Member,
				})
			}
		} else {
			// Repo with no IAM bindings
			body = append(body, []string{
				m.GetProjectName(repo.ProjectID),
				repo.Name,
				sizeDisplay,
				mirror,
				mirrorURL,
				triggers,
				"-",
				"-",
			})
		}
	}
	return body
}
