package commands

import (
	"context"
	"fmt"
	"strings"
	"sync"

	spannerservice "github.com/BishopFox/cloudfox/gcp/services/spannerService"
	"github.com/BishopFox/cloudfox/globals"
	"github.com/BishopFox/cloudfox/internal"
	gcpinternal "github.com/BishopFox/cloudfox/internal/gcp"
	"github.com/spf13/cobra"
)

var GCPSpannerCommand = &cobra.Command{
	Use:     globals.GCP_SPANNER_MODULE_NAME,
	Aliases: []string{"cloud-spanner"},
	Short:   "Enumerate Cloud Spanner instances and databases",
	Long: `Enumerate Cloud Spanner instances and databases with IAM bindings.

Features:
- Lists all Spanner instances with configuration details
- Shows databases within each instance with encryption info
- Enumerates IAM bindings at both instance and database levels
- Generates gcloud commands for further analysis`,
	Run: runGCPSpannerCommand,
}

type SpannerModule struct {
	gcpinternal.BaseGCPModule
	ProjectInstances map[string][]spannerservice.SpannerInstanceInfo // projectID -> instances
	ProjectDatabases map[string][]spannerservice.SpannerDatabaseInfo // projectID -> databases
	LootMap          map[string]map[string]*internal.LootFile        // projectID -> loot files
	mu               sync.Mutex
}

type SpannerOutput struct {
	Table []internal.TableFile
	Loot  []internal.LootFile
}

func (o SpannerOutput) TableFiles() []internal.TableFile { return o.Table }
func (o SpannerOutput) LootFiles() []internal.LootFile   { return o.Loot }

func runGCPSpannerCommand(cmd *cobra.Command, args []string) {
	cmdCtx, err := gcpinternal.InitializeCommandContext(cmd, globals.GCP_SPANNER_MODULE_NAME)
	if err != nil {
		return
	}

	module := &SpannerModule{
		BaseGCPModule:    gcpinternal.NewBaseGCPModule(cmdCtx),
		ProjectInstances: make(map[string][]spannerservice.SpannerInstanceInfo),
		ProjectDatabases: make(map[string][]spannerservice.SpannerDatabaseInfo),
		LootMap:          make(map[string]map[string]*internal.LootFile),
	}
	module.Execute(cmdCtx.Ctx, cmdCtx.Logger)
}

func (m *SpannerModule) Execute(ctx context.Context, logger internal.Logger) {
	m.RunProjectEnumeration(ctx, logger, m.ProjectIDs, globals.GCP_SPANNER_MODULE_NAME, m.processProject)

	allInstances := m.getAllInstances()
	allDatabases := m.getAllDatabases()

	if len(allInstances) == 0 {
		logger.InfoM("No Spanner instances found", globals.GCP_SPANNER_MODULE_NAME)
		return
	}

	logger.SuccessM(fmt.Sprintf("Found %d Spanner instance(s) with %d database(s)",
		len(allInstances), len(allDatabases)), globals.GCP_SPANNER_MODULE_NAME)
	m.writeOutput(ctx, logger)
}

func (m *SpannerModule) getAllInstances() []spannerservice.SpannerInstanceInfo {
	var all []spannerservice.SpannerInstanceInfo
	for _, instances := range m.ProjectInstances {
		all = append(all, instances...)
	}
	return all
}

func (m *SpannerModule) getAllDatabases() []spannerservice.SpannerDatabaseInfo {
	var all []spannerservice.SpannerDatabaseInfo
	for _, databases := range m.ProjectDatabases {
		all = append(all, databases...)
	}
	return all
}

func (m *SpannerModule) processProject(ctx context.Context, projectID string, logger internal.Logger) {
	if globals.GCP_VERBOSITY >= globals.GCP_VERBOSE_ERRORS {
		logger.InfoM(fmt.Sprintf("Enumerating Spanner in project: %s", projectID), globals.GCP_SPANNER_MODULE_NAME)
	}

	svc := spannerservice.New()
	result, err := svc.ListInstancesAndDatabases(projectID)
	if err != nil {
		m.CommandCounter.Error++
		gcpinternal.HandleGCPError(err, logger, globals.GCP_SPANNER_MODULE_NAME,
			fmt.Sprintf("Could not list Spanner instances in project %s", projectID))
		return
	}

	m.mu.Lock()
	m.ProjectInstances[projectID] = result.Instances
	m.ProjectDatabases[projectID] = result.Databases

	// Initialize loot for this project
	if m.LootMap[projectID] == nil {
		m.LootMap[projectID] = make(map[string]*internal.LootFile)
		m.LootMap[projectID]["spanner-commands"] = &internal.LootFile{
			Name:     "spanner-commands",
			Contents: "# Spanner Commands\n# Generated by CloudFox\n# WARNING: Only use with proper authorization\n\n",
		}
	}

	for _, instance := range result.Instances {
		m.addInstanceToLoot(projectID, instance)
	}
	for _, database := range result.Databases {
		m.addDatabaseToLoot(projectID, database)
	}
	m.mu.Unlock()

	if globals.GCP_VERBOSITY >= globals.GCP_VERBOSE_ERRORS {
		logger.InfoM(fmt.Sprintf("Found %d instance(s) and %d database(s) in project %s",
			len(result.Instances), len(result.Databases), projectID), globals.GCP_SPANNER_MODULE_NAME)
	}
}

func (m *SpannerModule) addInstanceToLoot(projectID string, instance spannerservice.SpannerInstanceInfo) {
	lootFile := m.LootMap[projectID]["spanner-commands"]
	if lootFile == nil {
		return
	}
	lootFile.Contents += fmt.Sprintf(
		"# =============================================================================\n"+
			"# INSTANCE: %s\n"+
			"# =============================================================================\n"+
			"# Project: %s\n"+
			"# Display Name: %s\n"+
			"# Config: %s\n"+
			"# Nodes: %d\n"+
			"# State: %s\n",
		instance.Name, instance.ProjectID,
		instance.DisplayName, instance.Config,
		instance.NodeCount, instance.State,
	)

	if len(instance.IAMBindings) > 0 {
		lootFile.Contents += "# IAM Bindings:\n"
		for _, binding := range instance.IAMBindings {
			lootFile.Contents += fmt.Sprintf("#   %s -> %s\n", binding.Role, binding.Member)
		}
	}

	lootFile.Contents += fmt.Sprintf(
		"\n# Describe instance:\n"+
			"gcloud spanner instances describe %s --project=%s\n\n"+
			"# List databases:\n"+
			"gcloud spanner databases list --instance=%s --project=%s\n\n"+
			"# Get IAM policy:\n"+
			"gcloud spanner instances get-iam-policy %s --project=%s\n\n",
		instance.Name, instance.ProjectID,
		instance.Name, instance.ProjectID,
		instance.Name, instance.ProjectID,
	)
}

func (m *SpannerModule) addDatabaseToLoot(projectID string, database spannerservice.SpannerDatabaseInfo) {
	lootFile := m.LootMap[projectID]["spanner-commands"]
	if lootFile == nil {
		return
	}
	lootFile.Contents += fmt.Sprintf(
		"# -----------------------------------------------------------------------------\n"+
			"# DATABASE: %s (Instance: %s)\n"+
			"# -----------------------------------------------------------------------------\n"+
			"# Project: %s\n"+
			"# State: %s\n"+
			"# Encryption: %s\n",
		database.Name, database.InstanceName,
		database.ProjectID, database.State,
		database.EncryptionType,
	)

	if database.KmsKeyName != "" {
		lootFile.Contents += fmt.Sprintf("# KMS Key: %s\n", database.KmsKeyName)
	}

	if len(database.IAMBindings) > 0 {
		lootFile.Contents += "# IAM Bindings:\n"
		for _, binding := range database.IAMBindings {
			lootFile.Contents += fmt.Sprintf("#   %s -> %s\n", binding.Role, binding.Member)
		}
	}

	lootFile.Contents += fmt.Sprintf(`
# === ENUMERATION COMMANDS ===

# Describe database:
gcloud spanner databases describe %s --instance=%s --project=%s

# Get database IAM policy:
gcloud spanner databases get-iam-policy %s --instance=%s --project=%s

# List all tables:
gcloud spanner databases execute-sql %s --instance=%s --project=%s --sql="SELECT * FROM INFORMATION_SCHEMA.TABLES"

# List all columns for all tables:
gcloud spanner databases execute-sql %s --instance=%s --project=%s --sql="SELECT TABLE_NAME, COLUMN_NAME, SPANNER_TYPE FROM INFORMATION_SCHEMA.COLUMNS ORDER BY TABLE_NAME"

# List indexes:
gcloud spanner databases execute-sql %s --instance=%s --project=%s --sql="SELECT * FROM INFORMATION_SCHEMA.INDEXES"

# Get DDL (schema dump):
gcloud spanner databases ddl describe %s --instance=%s --project=%s

`,
		database.Name, database.InstanceName, database.ProjectID,
		database.Name, database.InstanceName, database.ProjectID,
		database.Name, database.InstanceName, database.ProjectID,
		database.Name, database.InstanceName, database.ProjectID,
		database.Name, database.InstanceName, database.ProjectID,
		database.Name, database.InstanceName, database.ProjectID,
	)

	// === EXPLOIT COMMANDS ===
	lootFile.Contents += fmt.Sprintf(
		"# === EXPLOIT COMMANDS ===\n\n"+
			"# Dump data from tables (replace TABLE_NAME):\n"+
			"gcloud spanner databases execute-sql %s --instance=%s --project=%s --sql=\"SELECT * FROM TABLE_NAME LIMIT 100\"\n\n"+
			"# Dump all rows from a table:\n"+
			"gcloud spanner databases execute-sql %s --instance=%s --project=%s --sql=\"SELECT * FROM TABLE_NAME\" --format=json > /tmp/spanner-dump.json\n\n"+
			"# Search for sensitive data patterns:\n"+
			"gcloud spanner databases execute-sql %s --instance=%s --project=%s --sql=\"SELECT TABLE_NAME, COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE LOWER(COLUMN_NAME) LIKE '%%password%%' OR LOWER(COLUMN_NAME) LIKE '%%secret%%' OR LOWER(COLUMN_NAME) LIKE '%%token%%' OR LOWER(COLUMN_NAME) LIKE '%%key%%' OR LOWER(COLUMN_NAME) LIKE '%%credit%%' OR LOWER(COLUMN_NAME) LIKE '%%ssn%%'\"\n\n"+
			"# Create a backup (for exfiltration):\n"+
			"gcloud spanner backups create cloudfox-backup --instance=%s --database=%s --project=%s --expiration-date=$(date -u -d '+7 days' '+%%Y-%%m-%%dT%%H:%%M:%%SZ') --async\n\n"+
			"# Export database to GCS:\n"+
			"gcloud spanner databases export %s --instance=%s --project=%s --output-uri=gs://BUCKET_NAME/spanner-export/\n\n",
		database.Name, database.InstanceName, database.ProjectID,
		database.Name, database.InstanceName, database.ProjectID,
		database.Name, database.InstanceName, database.ProjectID,
		database.InstanceName, database.Name, database.ProjectID,
		database.Name, database.InstanceName, database.ProjectID,
	)
}

func (m *SpannerModule) writeOutput(ctx context.Context, logger internal.Logger) {
	if m.Hierarchy != nil && !m.FlatOutput {
		m.writeHierarchicalOutput(ctx, logger)
	} else {
		m.writeFlatOutput(ctx, logger)
	}
}

func (m *SpannerModule) getInstanceHeader() []string {
	return []string{
		"Project",
		"Instance",
		"Display Name",
		"Config",
		"Nodes",
		"State",
		"IAM Binding Role",
		"IAM Binding Principal",
	}
}

func (m *SpannerModule) getDatabaseHeader() []string {
	return []string{
		"Project",
		"Instance",
		"Database",
		"State",
		"Encryption",
		"KMS Key",
		"IAM Binding Role",
		"IAM Binding Principal",
	}
}

func (m *SpannerModule) instancesToTableBody(instances []spannerservice.SpannerInstanceInfo) [][]string {
	var body [][]string
	for _, instance := range instances {
		if len(instance.IAMBindings) > 0 {
			for _, binding := range instance.IAMBindings {
				body = append(body, []string{
					m.GetProjectName(instance.ProjectID),
					instance.Name,
					instance.DisplayName,
					instance.Config,
					fmt.Sprintf("%d", instance.NodeCount),
					instance.State,
					binding.Role,
					binding.Member,
				})
			}
		} else {
			// Instance with no IAM bindings
			body = append(body, []string{
				m.GetProjectName(instance.ProjectID),
				instance.Name,
				instance.DisplayName,
				instance.Config,
				fmt.Sprintf("%d", instance.NodeCount),
				instance.State,
				"-",
				"-",
			})
		}
	}
	return body
}

func (m *SpannerModule) databasesToTableBody(databases []spannerservice.SpannerDatabaseInfo) [][]string {
	var body [][]string
	for _, database := range databases {
		kmsKey := "-"
		if database.KmsKeyName != "" {
			kmsKey = database.KmsKeyName
		}

		if len(database.IAMBindings) > 0 {
			for _, binding := range database.IAMBindings {
				body = append(body, []string{
					m.GetProjectName(database.ProjectID),
					database.InstanceName,
					database.Name,
					database.State,
					database.EncryptionType,
					kmsKey,
					binding.Role,
					binding.Member,
				})
			}
		} else {
			// Database with no IAM bindings
			body = append(body, []string{
				m.GetProjectName(database.ProjectID),
				database.InstanceName,
				database.Name,
				database.State,
				database.EncryptionType,
				kmsKey,
				"-",
				"-",
			})
		}
	}
	return body
}

func (m *SpannerModule) buildTablesForProject(projectID string) []internal.TableFile {
	var tableFiles []internal.TableFile

	if instances, ok := m.ProjectInstances[projectID]; ok && len(instances) > 0 {
		tableFiles = append(tableFiles, internal.TableFile{
			Name:   "spanner-instances",
			Header: m.getInstanceHeader(),
			Body:   m.instancesToTableBody(instances),
		})
	}

	if databases, ok := m.ProjectDatabases[projectID]; ok && len(databases) > 0 {
		tableFiles = append(tableFiles, internal.TableFile{
			Name:   "spanner-databases",
			Header: m.getDatabaseHeader(),
			Body:   m.databasesToTableBody(databases),
		})
	}

	return tableFiles
}

func (m *SpannerModule) writeHierarchicalOutput(ctx context.Context, logger internal.Logger) {
	outputData := internal.HierarchicalOutputData{
		OrgLevelData:     make(map[string]internal.CloudfoxOutput),
		ProjectLevelData: make(map[string]internal.CloudfoxOutput),
	}

	// Get all project IDs that have data
	projectIDs := make(map[string]bool)
	for projectID := range m.ProjectInstances {
		projectIDs[projectID] = true
	}
	for projectID := range m.ProjectDatabases {
		projectIDs[projectID] = true
	}

	for projectID := range projectIDs {
		tableFiles := m.buildTablesForProject(projectID)

		var lootFiles []internal.LootFile
		if projectLoot, ok := m.LootMap[projectID]; ok {
			for _, loot := range projectLoot {
				if loot != nil && loot.Contents != "" && !strings.HasSuffix(loot.Contents, "# WARNING: Only use with proper authorization\n\n") {
					lootFiles = append(lootFiles, *loot)
				}
			}
		}

		outputData.ProjectLevelData[projectID] = SpannerOutput{Table: tableFiles, Loot: lootFiles}
	}

	pathBuilder := m.BuildPathBuilder()

	err := internal.HandleHierarchicalOutputSmart("gcp", m.Format, m.Verbosity, m.WrapTable, pathBuilder, outputData)
	if err != nil {
		logger.ErrorM(fmt.Sprintf("Error writing hierarchical output: %v", err), globals.GCP_SPANNER_MODULE_NAME)
	}
}

func (m *SpannerModule) writeFlatOutput(ctx context.Context, logger internal.Logger) {
	allInstances := m.getAllInstances()
	allDatabases := m.getAllDatabases()

	var tables []internal.TableFile

	if len(allInstances) > 0 {
		tables = append(tables, internal.TableFile{
			Name:   "spanner-instances",
			Header: m.getInstanceHeader(),
			Body:   m.instancesToTableBody(allInstances),
		})
	}

	if len(allDatabases) > 0 {
		tables = append(tables, internal.TableFile{
			Name:   "spanner-databases",
			Header: m.getDatabaseHeader(),
			Body:   m.databasesToTableBody(allDatabases),
		})
	}

	var lootFiles []internal.LootFile
	for _, projectLoot := range m.LootMap {
		for _, loot := range projectLoot {
			if loot != nil && loot.Contents != "" && !strings.HasSuffix(loot.Contents, "# WARNING: Only use with proper authorization\n\n") {
				lootFiles = append(lootFiles, *loot)
			}
		}
	}

	output := SpannerOutput{
		Table: tables,
		Loot:  lootFiles,
	}

	scopeNames := make([]string, len(m.ProjectIDs))
	for i, id := range m.ProjectIDs {
		scopeNames[i] = m.GetProjectName(id)
	}

	err := internal.HandleOutputSmart("gcp", m.Format, m.OutputDirectory, m.Verbosity, m.WrapTable,
		"project", m.ProjectIDs, scopeNames, m.Account, output)
	if err != nil {
		logger.ErrorM(fmt.Sprintf("Error writing output: %v", err), globals.GCP_SPANNER_MODULE_NAME)
		m.CommandCounter.Error++
	}
}
