package commands

import (
	"context"
	"fmt"
	"strings"
	"sync"

	diagramservice "github.com/BishopFox/cloudfox/gcp/services/diagramService"
	vpcservice "github.com/BishopFox/cloudfox/gcp/services/vpcService"
	"github.com/BishopFox/cloudfox/globals"
	"github.com/BishopFox/cloudfox/internal"
	gcpinternal "github.com/BishopFox/cloudfox/internal/gcp"
	"github.com/spf13/cobra"
)

var GCPVPCNetworksCommand = &cobra.Command{
	Use:     globals.GCP_VPCNETWORKS_MODULE_NAME,
	Aliases: []string{"vpc", "networks", "net"},
	Short:   "Enumerate VPC Networks",
	Long: `Enumerate VPC Networks and related configurations.

Features:
- Lists all VPC networks and subnets
- Shows VPC peering connections
- Analyzes routing tables
- Checks for Private Google Access
- Identifies flow log configuration`,
	Run: runGCPVPCNetworksCommand,
}

type VPCNetworksModule struct {
	gcpinternal.BaseGCPModule
	ProjectNetworks map[string][]vpcservice.VPCNetworkInfo  // projectID -> networks
	ProjectSubnets  map[string][]vpcservice.SubnetInfo      // projectID -> subnets
	ProjectPeerings map[string][]vpcservice.VPCPeeringInfo  // projectID -> peerings
	ProjectRoutes   map[string][]vpcservice.RouteInfo       // projectID -> routes
	LootMap         map[string]map[string]*internal.LootFile // projectID -> loot files
	mu              sync.Mutex
}

type VPCNetworksOutput struct {
	Table []internal.TableFile
	Loot  []internal.LootFile
}

func (o VPCNetworksOutput) TableFiles() []internal.TableFile { return o.Table }
func (o VPCNetworksOutput) LootFiles() []internal.LootFile   { return o.Loot }

func runGCPVPCNetworksCommand(cmd *cobra.Command, args []string) {
	cmdCtx, err := gcpinternal.InitializeCommandContext(cmd, globals.GCP_VPCNETWORKS_MODULE_NAME)
	if err != nil {
		return
	}

	module := &VPCNetworksModule{
		BaseGCPModule:   gcpinternal.NewBaseGCPModule(cmdCtx),
		ProjectNetworks: make(map[string][]vpcservice.VPCNetworkInfo),
		ProjectSubnets:  make(map[string][]vpcservice.SubnetInfo),
		ProjectPeerings: make(map[string][]vpcservice.VPCPeeringInfo),
		ProjectRoutes:   make(map[string][]vpcservice.RouteInfo),
		LootMap:         make(map[string]map[string]*internal.LootFile),
	}
	module.Execute(cmdCtx.Ctx, cmdCtx.Logger)
}

func (m *VPCNetworksModule) Execute(ctx context.Context, logger internal.Logger) {
	m.RunProjectEnumeration(ctx, logger, m.ProjectIDs, globals.GCP_VPCNETWORKS_MODULE_NAME, m.processProject)

	allNetworks := m.getAllNetworks()
	allSubnets := m.getAllSubnets()
	allPeerings := m.getAllPeerings()
	allRoutes := m.getAllRoutes()

	if len(allNetworks) == 0 {
		logger.InfoM("No VPC networks found", globals.GCP_VPCNETWORKS_MODULE_NAME)
		return
	}

	logger.SuccessM(fmt.Sprintf("Found %d VPC network(s), %d subnet(s), %d peering(s), %d route(s)",
		len(allNetworks), len(allSubnets), len(allPeerings), len(allRoutes)), globals.GCP_VPCNETWORKS_MODULE_NAME)
	m.writeOutput(ctx, logger)
}

func (m *VPCNetworksModule) getAllNetworks() []vpcservice.VPCNetworkInfo {
	var all []vpcservice.VPCNetworkInfo
	for _, networks := range m.ProjectNetworks {
		all = append(all, networks...)
	}
	return all
}

func (m *VPCNetworksModule) getAllSubnets() []vpcservice.SubnetInfo {
	var all []vpcservice.SubnetInfo
	for _, subnets := range m.ProjectSubnets {
		all = append(all, subnets...)
	}
	return all
}

func (m *VPCNetworksModule) getAllPeerings() []vpcservice.VPCPeeringInfo {
	var all []vpcservice.VPCPeeringInfo
	for _, peerings := range m.ProjectPeerings {
		all = append(all, peerings...)
	}
	return all
}

func (m *VPCNetworksModule) getAllRoutes() []vpcservice.RouteInfo {
	var all []vpcservice.RouteInfo
	for _, routes := range m.ProjectRoutes {
		all = append(all, routes...)
	}
	return all
}

func (m *VPCNetworksModule) processProject(ctx context.Context, projectID string, logger internal.Logger) {
	if globals.GCP_VERBOSITY >= globals.GCP_VERBOSE_ERRORS {
		logger.InfoM(fmt.Sprintf("Enumerating VPC networks in project: %s", projectID), globals.GCP_VPCNETWORKS_MODULE_NAME)
	}

	svc := vpcservice.New()

	m.mu.Lock()
	// Initialize loot for this project
	if m.LootMap[projectID] == nil {
		m.LootMap[projectID] = make(map[string]*internal.LootFile)
		m.LootMap[projectID]["vpcnetworks-commands"] = &internal.LootFile{
			Name:     "vpcnetworks-commands",
			Contents: "# VPC Networks Commands\n# Generated by CloudFox\n# WARNING: Only use with proper authorization\n# See also: network-topology-commands for comprehensive topology with NAT/SharedVPC\n\n",
		}
	}
	m.mu.Unlock()

	// Get networks
	networks, err := svc.ListVPCNetworks(projectID)
	if err != nil {
		m.CommandCounter.Error++
		gcpinternal.HandleGCPError(err, logger, globals.GCP_VPCNETWORKS_MODULE_NAME,
			fmt.Sprintf("Could not list VPC networks in project %s", projectID))
	} else {
		m.mu.Lock()
		m.ProjectNetworks[projectID] = networks
		for _, network := range networks {
			m.addNetworkToLoot(projectID, network)
		}
		m.mu.Unlock()
	}

	// Get subnets
	subnets, err := svc.ListSubnets(projectID)
	if err != nil {
		m.CommandCounter.Error++
		gcpinternal.HandleGCPError(err, logger, globals.GCP_VPCNETWORKS_MODULE_NAME,
			fmt.Sprintf("Could not list subnets in project %s", projectID))
	} else {
		m.mu.Lock()
		m.ProjectSubnets[projectID] = subnets
		for _, subnet := range subnets {
			m.addSubnetToLoot(projectID, subnet)
		}
		m.mu.Unlock()
	}

	// Get peerings
	peerings, err := svc.ListVPCPeerings(projectID)
	if err != nil {
		m.CommandCounter.Error++
		gcpinternal.HandleGCPError(err, logger, globals.GCP_VPCNETWORKS_MODULE_NAME,
			fmt.Sprintf("Could not list VPC peerings in project %s", projectID))
	} else {
		m.mu.Lock()
		m.ProjectPeerings[projectID] = peerings
		for _, peering := range peerings {
			m.addPeeringToLoot(projectID, peering)
		}
		m.mu.Unlock()
	}

	// Get routes
	routes, err := svc.ListRoutes(projectID)
	if err != nil {
		m.CommandCounter.Error++
		gcpinternal.HandleGCPError(err, logger, globals.GCP_VPCNETWORKS_MODULE_NAME,
			fmt.Sprintf("Could not list routes in project %s", projectID))
	} else {
		m.mu.Lock()
		m.ProjectRoutes[projectID] = routes
		m.mu.Unlock()
	}
}

func (m *VPCNetworksModule) addNetworkToLoot(projectID string, network vpcservice.VPCNetworkInfo) {
	lootFile := m.LootMap[projectID]["vpcnetworks-commands"]
	if lootFile == nil {
		return
	}
	lootFile.Contents += fmt.Sprintf(
		"# =============================================================================\n"+
			"# NETWORK: %s\n"+
			"# =============================================================================\n"+
			"# Project: %s\n"+
			"# Routing Mode: %s\n"+
			"# Auto Create Subnets: %v\n"+
			"# Subnets: %d\n"+
			"# Peerings: %d\n"+
			"\n# Describe network:\n"+
			"gcloud compute networks describe %s --project=%s\n\n"+
			"# List subnets in network:\n"+
			"gcloud compute networks subnets list --network=%s --project=%s\n\n"+
			"# List peerings:\n"+
			"gcloud compute networks peerings list --network=%s --project=%s\n\n",
		network.Name,
		network.ProjectID,
		network.RoutingMode,
		network.AutoCreateSubnetworks,
		len(network.Subnetworks),
		len(network.Peerings),
		network.Name, network.ProjectID,
		network.Name, network.ProjectID,
		network.Name, network.ProjectID,
	)
}

func (m *VPCNetworksModule) addSubnetToLoot(projectID string, subnet vpcservice.SubnetInfo) {
	lootFile := m.LootMap[projectID]["vpcnetworks-commands"]
	if lootFile == nil {
		return
	}
	lootFile.Contents += fmt.Sprintf(
		"# -----------------------------------------------------------------------------\n"+
			"# SUBNET: %s (Network: %s)\n"+
			"# -----------------------------------------------------------------------------\n"+
			"# Project: %s\n"+
			"# Region: %s\n"+
			"# CIDR: %s\n"+
			"# Private Google Access: %v\n"+
			"# Flow Logs: %v\n"+
			"\n# Describe subnet:\n"+
			"gcloud compute networks subnets describe %s --region=%s --project=%s\n\n",
		subnet.Name, subnet.Network,
		subnet.ProjectID,
		subnet.Region,
		subnet.IPCidrRange,
		subnet.PrivateIPGoogleAccess,
		subnet.EnableFlowLogs,
		subnet.Name, subnet.Region, subnet.ProjectID,
	)
}

func (m *VPCNetworksModule) addPeeringToLoot(projectID string, peering vpcservice.VPCPeeringInfo) {
	lootFile := m.LootMap[projectID]["vpcnetworks-commands"]
	if lootFile == nil {
		return
	}
	lootFile.Contents += fmt.Sprintf(
		"# -----------------------------------------------------------------------------\n"+
			"# PEERING: %s\n"+
			"# -----------------------------------------------------------------------------\n"+
			"# Project: %s\n"+
			"# Network: %s -> Peer Network: %s\n"+
			"# Peer Project: %s\n"+
			"# State: %s\n"+
			"# Export Routes: %v, Import Routes: %v\n",
		peering.Name,
		peering.ProjectID,
		peering.Network, peering.PeerNetwork,
		peering.PeerProjectID,
		peering.State,
		peering.ExportCustomRoutes, peering.ImportCustomRoutes,
	)

	// Cross-project peering commands
	if peering.PeerProjectID != "" && peering.PeerProjectID != peering.ProjectID {
		lootFile.Contents += fmt.Sprintf(
			"\n# Cross-project peering - enumerate peer project:\n"+
				"gcloud compute instances list --project=%s\n"+
				"gcloud compute networks subnets list --project=%s\n\n",
			peering.PeerProjectID,
			peering.PeerProjectID,
		)
	} else {
		lootFile.Contents += "\n"
	}
}

func (m *VPCNetworksModule) writeOutput(ctx context.Context, logger internal.Logger) {
	// Generate ASCII diagram and add to loot
	diagram := m.generateVPCNetworksDiagram()
	if diagram != "" {
		// Add diagram to the first project's loot
		for projectID := range m.LootMap {
			if m.LootMap[projectID] == nil {
				m.LootMap[projectID] = make(map[string]*internal.LootFile)
			}
			m.LootMap[projectID]["vpcnetworks-diagram"] = &internal.LootFile{
				Name:     "vpcnetworks-diagram",
				Contents: diagram,
			}
			break // Only add once for flat output
		}

		// For hierarchical output, add to all projects
		if m.Hierarchy != nil && !m.FlatOutput {
			for projectID := range m.LootMap {
				if m.LootMap[projectID] == nil {
					m.LootMap[projectID] = make(map[string]*internal.LootFile)
				}
				m.LootMap[projectID]["vpcnetworks-diagram"] = &internal.LootFile{
					Name:     "vpcnetworks-diagram",
					Contents: diagram,
				}
			}
		}
	}

	if m.Hierarchy != nil && !m.FlatOutput {
		m.writeHierarchicalOutput(ctx, logger)
	} else {
		m.writeFlatOutput(ctx, logger)
	}
}

// ------------------------------
// Diagram Generation
// ------------------------------

// generateVPCNetworksDiagram creates an ASCII visualization of VPC networks
func (m *VPCNetworksModule) generateVPCNetworksDiagram() string {
	allNetworks := m.getAllNetworks()
	if len(allNetworks) == 0 {
		return ""
	}

	// Convert networks to diagram service types
	diagramNetworks := make([]diagramservice.NetworkInfo, 0, len(allNetworks))
	for _, n := range allNetworks {
		diagramNetworks = append(diagramNetworks, diagramservice.NetworkInfo{
			Name:          n.Name,
			ProjectID:     n.ProjectID,
			RoutingMode:   n.RoutingMode,
			MTU:           0, // VPCNetworkInfo doesn't have MTU
			IsSharedVPC:   false,
			SharedVPCRole: "",
			PeeringCount:  len(n.Peerings),
		})
	}

	// Build subnets by network
	subnetsByNetwork := make(map[string][]diagramservice.SubnetInfo)
	for _, s := range m.getAllSubnets() {
		key := s.ProjectID + "/" + s.Network
		subnetsByNetwork[key] = append(subnetsByNetwork[key], diagramservice.SubnetInfo{
			Name:                  s.Name,
			Region:                s.Region,
			IPCIDRRange:           s.IPCidrRange,
			PrivateIPGoogleAccess: s.PrivateIPGoogleAccess,
			FlowLogsEnabled:       s.EnableFlowLogs,
		})
	}

	// Convert peerings to diagram service types
	diagramPeerings := make([]diagramservice.VPCPeeringInfo, 0, len(m.getAllPeerings()))
	for _, p := range m.getAllPeerings() {
		diagramPeerings = append(diagramPeerings, diagramservice.VPCPeeringInfo{
			Name:          p.Name,
			Network:       p.Network,
			PeerNetwork:   p.PeerNetwork,
			PeerProjectID: p.PeerProjectID,
			State:         p.State,
			ExportRoutes:  p.ExportCustomRoutes,
			ImportRoutes:  p.ImportCustomRoutes,
		})
	}

	// Determine project ID for header (use first project if multiple)
	projectID := ""
	if len(m.ProjectIDs) == 1 {
		projectID = m.ProjectIDs[0]
	}

	return diagramservice.DrawVPCNetworksDiagram(diagramNetworks, subnetsByNetwork, diagramPeerings, projectID, 90)
}

func (m *VPCNetworksModule) getNetworksHeader() []string {
	return []string{"Project", "Name", "Routing Mode", "Auto Subnets", "Subnets", "Peerings"}
}

func (m *VPCNetworksModule) getSubnetsHeader() []string {
	return []string{"Project", "Name", "Network", "Region", "CIDR", "Private Access", "Flow Logs"}
}

func (m *VPCNetworksModule) getPeeringsHeader() []string {
	return []string{"Project", "Name", "Network", "Peer Network", "Peer Project", "State", "Export Routes", "Import Routes"}
}

func (m *VPCNetworksModule) getRoutesHeader() []string {
	return []string{"Project", "Name", "Network", "Dest Range", "Next Hop Type", "Next Hop", "Priority"}
}

func (m *VPCNetworksModule) networksToTableBody(networks []vpcservice.VPCNetworkInfo) [][]string {
	var body [][]string
	for _, network := range networks {
		autoSubnets := "No"
		if network.AutoCreateSubnetworks {
			autoSubnets = "Yes"
		}
		body = append(body, []string{
			m.GetProjectName(network.ProjectID),
			network.Name,
			network.RoutingMode,
			autoSubnets,
			fmt.Sprintf("%d", len(network.Subnetworks)),
			fmt.Sprintf("%d", len(network.Peerings)),
		})
	}
	return body
}

func (m *VPCNetworksModule) subnetsToTableBody(subnets []vpcservice.SubnetInfo) [][]string {
	var body [][]string
	for _, subnet := range subnets {
		privateAccess := "No"
		if subnet.PrivateIPGoogleAccess {
			privateAccess = "Yes"
		}
		flowLogs := "No"
		if subnet.EnableFlowLogs {
			flowLogs = "Yes"
		}
		body = append(body, []string{
			m.GetProjectName(subnet.ProjectID),
			subnet.Name,
			subnet.Network,
			subnet.Region,
			subnet.IPCidrRange,
			privateAccess,
			flowLogs,
		})
	}
	return body
}

func (m *VPCNetworksModule) peeringsToTableBody(peerings []vpcservice.VPCPeeringInfo) [][]string {
	var body [][]string
	for _, peering := range peerings {
		peerProject := peering.PeerProjectID
		if peerProject == "" {
			peerProject = "-"
		}
		exportRoutes := "No"
		if peering.ExportCustomRoutes {
			exportRoutes = "Yes"
		}
		importRoutes := "No"
		if peering.ImportCustomRoutes {
			importRoutes = "Yes"
		}
		body = append(body, []string{
			m.GetProjectName(peering.ProjectID),
			peering.Name,
			peering.Network,
			peering.PeerNetwork,
			peerProject,
			peering.State,
			exportRoutes,
			importRoutes,
		})
	}
	return body
}

func (m *VPCNetworksModule) routesToTableBody(routes []vpcservice.RouteInfo) [][]string {
	var body [][]string
	// Filter to custom routes only
	for _, route := range routes {
		if strings.HasPrefix(route.Name, "default-route-") {
			continue
		}
		body = append(body, []string{
			m.GetProjectName(route.ProjectID),
			route.Name,
			route.Network,
			route.DestRange,
			route.NextHopType,
			route.NextHop,
			fmt.Sprintf("%d", route.Priority),
		})
	}
	return body
}

func (m *VPCNetworksModule) buildTablesForProject(projectID string) []internal.TableFile {
	var tableFiles []internal.TableFile

	if networks, ok := m.ProjectNetworks[projectID]; ok && len(networks) > 0 {
		tableFiles = append(tableFiles, internal.TableFile{
			Name:   "vpc-networks",
			Header: m.getNetworksHeader(),
			Body:   m.networksToTableBody(networks),
		})
	}

	if subnets, ok := m.ProjectSubnets[projectID]; ok && len(subnets) > 0 {
		tableFiles = append(tableFiles, internal.TableFile{
			Name:   "subnets",
			Header: m.getSubnetsHeader(),
			Body:   m.subnetsToTableBody(subnets),
		})
	}

	if peerings, ok := m.ProjectPeerings[projectID]; ok && len(peerings) > 0 {
		tableFiles = append(tableFiles, internal.TableFile{
			Name:   "vpc-peerings",
			Header: m.getPeeringsHeader(),
			Body:   m.peeringsToTableBody(peerings),
		})
	}

	if routes, ok := m.ProjectRoutes[projectID]; ok && len(routes) > 0 {
		routeBody := m.routesToTableBody(routes)
		if len(routeBody) > 0 {
			tableFiles = append(tableFiles, internal.TableFile{
				Name:   "custom-routes",
				Header: m.getRoutesHeader(),
				Body:   routeBody,
			})
		}
	}

	return tableFiles
}

func (m *VPCNetworksModule) writeHierarchicalOutput(ctx context.Context, logger internal.Logger) {
	outputData := internal.HierarchicalOutputData{
		OrgLevelData:     make(map[string]internal.CloudfoxOutput),
		ProjectLevelData: make(map[string]internal.CloudfoxOutput),
	}

	// Get all project IDs that have data
	projectIDs := make(map[string]bool)
	for projectID := range m.ProjectNetworks {
		projectIDs[projectID] = true
	}
	for projectID := range m.ProjectSubnets {
		projectIDs[projectID] = true
	}
	for projectID := range m.ProjectPeerings {
		projectIDs[projectID] = true
	}
	for projectID := range m.ProjectRoutes {
		projectIDs[projectID] = true
	}

	for projectID := range projectIDs {
		tableFiles := m.buildTablesForProject(projectID)

		var lootFiles []internal.LootFile
		if projectLoot, ok := m.LootMap[projectID]; ok {
			for _, loot := range projectLoot {
				if loot != nil && loot.Contents != "" && !strings.HasSuffix(loot.Contents, "# WARNING: Only use with proper authorization\n\n") {
					lootFiles = append(lootFiles, *loot)
				}
			}
		}

		outputData.ProjectLevelData[projectID] = VPCNetworksOutput{Table: tableFiles, Loot: lootFiles}
	}

	pathBuilder := m.BuildPathBuilder()

	err := internal.HandleHierarchicalOutputSmart("gcp", m.Format, m.Verbosity, m.WrapTable, pathBuilder, outputData)
	if err != nil {
		logger.ErrorM(fmt.Sprintf("Error writing hierarchical output: %v", err), globals.GCP_VPCNETWORKS_MODULE_NAME)
	}
}

func (m *VPCNetworksModule) writeFlatOutput(ctx context.Context, logger internal.Logger) {
	allNetworks := m.getAllNetworks()
	allSubnets := m.getAllSubnets()
	allPeerings := m.getAllPeerings()
	allRoutes := m.getAllRoutes()

	var tables []internal.TableFile

	if len(allNetworks) > 0 {
		tables = append(tables, internal.TableFile{
			Name:   "vpc-networks",
			Header: m.getNetworksHeader(),
			Body:   m.networksToTableBody(allNetworks),
		})
	}

	if len(allSubnets) > 0 {
		tables = append(tables, internal.TableFile{
			Name:   "subnets",
			Header: m.getSubnetsHeader(),
			Body:   m.subnetsToTableBody(allSubnets),
		})
	}

	if len(allPeerings) > 0 {
		tables = append(tables, internal.TableFile{
			Name:   "vpc-peerings",
			Header: m.getPeeringsHeader(),
			Body:   m.peeringsToTableBody(allPeerings),
		})
	}

	routeBody := m.routesToTableBody(allRoutes)
	if len(routeBody) > 0 {
		tables = append(tables, internal.TableFile{
			Name:   "custom-routes",
			Header: m.getRoutesHeader(),
			Body:   routeBody,
		})
	}

	var lootFiles []internal.LootFile
	for _, projectLoot := range m.LootMap {
		for _, loot := range projectLoot {
			if loot != nil && loot.Contents != "" && !strings.HasSuffix(loot.Contents, "# WARNING: Only use with proper authorization\n\n") {
				lootFiles = append(lootFiles, *loot)
			}
		}
	}

	output := VPCNetworksOutput{Table: tables, Loot: lootFiles}

	scopeNames := make([]string, len(m.ProjectIDs))
	for i, id := range m.ProjectIDs {
		scopeNames[i] = m.GetProjectName(id)
	}

	err := internal.HandleOutputSmart("gcp", m.Format, m.OutputDirectory, m.Verbosity, m.WrapTable,
		"project", m.ProjectIDs, scopeNames, m.Account, output)
	if err != nil {
		logger.ErrorM(fmt.Sprintf("Error writing output: %v", err), globals.GCP_VPCNETWORKS_MODULE_NAME)
	}
}
