name: Create Releases
on:
  push:
    tags: v[0-9]+.[0-9]+.[0-9]+
    branches: main

  workflow_dispatch:

jobs:

  tagged-release:
    name: "Tagged Release"
    if: startsWith( github.ref, 'refs/tags/v')
    runs-on: "ubuntu-latest"

    steps:

      - name: Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: ^1.20
        id: go

      - id: install-secret-key
        name: GPG Secret Key(s)
        run: |
          cat <(echo -e "${{ secrets.CLOUDFOX_GPG }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG

      - name: Check Out Code
        uses: actions/checkout@v4

      - name: Git Fetch Tags
        run: git fetch --prune --unshallow --tags -f

      - name: Make binaries
        working-directory: .
        run: make release

       
      - name: Release binaries
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            ./cloudfox/*
